export interface GlossaryTerm {
  term: string
  definition: string
}

export interface GlossaryCategory {
  category: string
  terms: GlossaryTerm[]
}

export const glossaryByCategory: GlossaryCategory[] = [
  {
    category: "Terminologia Anatômica",
    terms: [
      { term: "Anatomia", definition: "Ciência que estuda a estrutura do corpo humano e suas partes." },
      { term: "Anterior", definition: "Posição na frente do corpo ou de uma estrutura." },
      { term: "Posterior", definition: "Posição atrás do corpo ou de uma estrutura." },
      { term: "Medial", definition: "Mais próximo da linha média do corpo." },
      { term: "Lateral", definition: "Mais afastado da linha média do corpo." },
      { term: "Proximal", definition: "Mais próximo do ponto de origem ou do tronco." },
      { term: "Distal", definition: "Mais afastado do ponto de origem ou do tronco." },
      { term: "Superior", definition: "Acima ou em direção à cabeça." },
      { term: "Inferior", definition: "Abaixo ou em direção aos pés." },
      { term: "Superficial", definition: "Mais próximo da superfície do corpo." },
      { term: "Profundo", definition: "Mais afastado da superfície do corpo." },
      { term: "Ventral", definition: "Relativo à parte anterior do corpo." },
      { term: "Dorsal", definition: "Relativo à parte posterior do corpo." },
      { term: "Cranial", definition: "Em direção à cabeça." },
      { term: "Caudal", definition: "Em direção à cauda ou extremidade inferior." },
      { term: "Ipsilateral", definition: "Do mesmo lado do corpo." },
      { term: "Contralateral", definition: "Do lado oposto do corpo." },
      { term: "Plano Sagital", definition: "Plano vertical que divide o corpo em partes direita e esquerda." },
      { term: "Plano Coronal", definition: "Plano vertical que divide o corpo em partes anterior e posterior." },
      { term: "Plano Transversal", definition: "Plano horizontal que divide o corpo em partes superior e inferior." },
    ],
  },
  {
    category: "Sistema Esquelético",
    terms: [
      {
        term: "Esqueleto Axial",
        definition: "Parte do esqueleto formada por crânio, coluna vertebral e caixa torácica.",
      },
      {
        term: "Esqueleto Apendicular",
        definition: "Parte do esqueleto formada pelos membros superiores e inferiores.",
      },
      { term: "Vértebra", definition: "Osso individual que compõe a coluna vertebral." },
      { term: "Forame", definition: "Abertura ou orifício em um osso por onde passam nervos e vasos." },
      { term: "Sutura", definition: "Articulação fibrosa imóvel entre ossos do crânio." },
      { term: "Crânio", definition: "Estrutura óssea que protege o encéfalo e forma a cabeça." },
      { term: "Neurocrânio", definition: "Parte do crânio que envolve e protege o encéfalo." },
      { term: "Viscerocrânio", definition: "Parte do crânio que forma a face e estruturas relacionadas." },
      { term: "Mandíbula", definition: "Osso móvel da face que forma a arcada dentária inferior." },
      { term: "Maxila", definition: "Osso da face que forma a arcada dentária superior." },
      { term: "Costela", definition: "Osso curvo que forma a caixa torácica." },
      { term: "Esterno", definition: "Osso plano central da caixa torácica." },
      { term: "Osteologia", definition: "Estudo científico dos ossos e do sistema esquelético." },
    ],
  },
  {
    category: "Sistema Articular",
    terms: [
      { term: "Articulação", definition: "Ponto de conexão entre dois ou mais ossos." },
      { term: "Ligamento", definition: "Tecido conjuntivo fibroso que conecta ossos entre si." },
      { term: "ATM", definition: "Articulação Temporomandibular - articulação entre mandíbula e crânio." },
      { term: "Sinartrose", definition: "Articulação fibrosa com pouco ou nenhum movimento." },
      { term: "Anfiartrose", definition: "Articulação cartilaginosa com movimento limitado." },
      { term: "Diartrose", definition: "Articulação sinovial com ampla mobilidade." },
      { term: "Cápsula Articular", definition: "Estrutura fibrosa que envolve articulações sinoviais." },
      { term: "Líquido Sinovial", definition: "Fluido lubrificante presente em articulações móveis." },
      { term: "Cartilagem Articular", definition: "Tecido que reveste superfícies ósseas em articulações." },
      { term: "Menisco", definition: "Estrutura fibrocartilaginosa em algumas articulações como o joelho." },
      { term: "Bursa", definition: "Bolsa sinovial que reduz atrito entre estruturas." },
      { term: "Artrologia", definition: "Estudo científico das articulações e suas estruturas." },
    ],
  },
  {
    category: "Sistema Muscular",
    terms: [
      { term: "Músculo", definition: "Tecido contrátil responsável pelo movimento do corpo." },
      { term: "Tendão", definition: "Tecido conjuntivo fibroso que conecta músculos aos ossos." },
      { term: "Origem Muscular", definition: "Ponto de fixação proximal e menos móvel de um músculo." },
      { term: "Inserção Muscular", definition: "Ponto de fixação distal e mais móvel de um músculo." },
      { term: "Agonista", definition: "Músculo principal responsável por um movimento específico." },
      { term: "Antagonista", definition: "Músculo que se opõe à ação do agonista." },
      { term: "Sinergista", definition: "Músculo que auxilia o agonista em um movimento." },
      { term: "Fáscia", definition: "Camada de tecido conjuntivo que envolve músculos e órgãos." },
      { term: "Aponeurose", definition: "Lâmina tendinosa plana que conecta músculos." },
      { term: "Diafragma", definition: "Músculo principal da respiração que separa tórax e abdome." },
      {
        term: "Músculo Esternocleidomastóideo",
        definition: "Músculo do pescoço que permite rotação e flexão da cabeça.",
      },
      { term: "Miologia", definition: "Estudo científico dos músculos e suas funções." },
      { term: "Miótomo", definition: "Músculos inervados por um único nervo espinal." },
    ],
  },
  {
    category: "Movimentos Articulares",
    terms: [
      { term: "Flexão", definition: "Movimento que diminui o ângulo entre duas partes do corpo." },
      { term: "Extensão", definition: "Movimento que aumenta o ângulo entre duas partes do corpo." },
      { term: "Abdução", definition: "Movimento de afastamento da linha média do corpo." },
      { term: "Adução", definition: "Movimento de aproximação em direção à linha média do corpo." },
      { term: "Rotação", definition: "Movimento circular ao redor de um eixo." },
      { term: "Circundução", definition: "Movimento circular combinando flexão, extensão, abdução e adução." },
      { term: "Pronação", definition: "Rotação do antebraço que posiciona a palma para baixo." },
      { term: "Supinação", definition: "Rotação do antebraço que posiciona a palma para cima." },
      { term: "Inversão", definition: "Movimento da planta do pé em direção à linha média." },
      { term: "Eversão", definition: "Movimento da planta do pé para fora da linha média." },
      { term: "Dorsiflexão", definition: "Movimento que aproxima o dorso do pé da perna." },
      { term: "Flexão Plantar", definition: "Movimento que afasta o dorso do pé da perna." },
      { term: "Protração", definition: "Movimento anterior de uma estrutura, como a mandíbula." },
      { term: "Retração", definition: "Movimento posterior de uma estrutura." },
      { term: "Elevação", definition: "Movimento superior de uma estrutura, como os ombros." },
      { term: "Depressão", definition: "Movimento inferior de uma estrutura." },
      { term: "Oposição", definition: "Movimento do polegar em direção aos outros dedos." },
      { term: "Reposição", definition: "Retorno do polegar à posição anatômica." },
    ],
  },
  {
    category: "Sistema Cardiovascular",
    terms: [
      { term: "Coração", definition: "Órgão muscular que bombeia sangue pelo corpo." },
      { term: "Átrio", definition: "Câmara superior do coração que recebe sangue." },
      { term: "Ventrículo", definition: "Câmara inferior do coração que bombeia sangue." },
      { term: "Valva", definition: "Estrutura que controla o fluxo sanguíneo no coração." },
      { term: "Pericárdio", definition: "Membrana que envolve e protege o coração." },
      { term: "Miocárdio", definition: "Camada muscular do coração responsável pela contração." },
      { term: "Endocárdio", definition: "Camada interna que reveste as câmaras cardíacas." },
      { term: "Artéria", definition: "Vaso sanguíneo que transporta sangue do coração para os tecidos." },
      { term: "Veia", definition: "Vaso sanguíneo que transporta sangue dos tecidos para o coração." },
      { term: "Capilar", definition: "Vaso sanguíneo microscópico onde ocorrem as trocas gasosas e de nutrientes." },
      { term: "Aorta", definition: "Maior artéria do corpo que se origina do ventrículo esquerdo." },
      { term: "Veia Cava", definition: "Grande veia que retorna sangue ao átrio direito." },
      { term: "Artéria Pulmonar", definition: "Vaso que transporta sangue do coração aos pulmões." },
      { term: "Veia Pulmonar", definition: "Vaso que retorna sangue oxigenado dos pulmões ao coração." },
      { term: "Artéria Carótida", definition: "Principal artéria que irriga cabeça e pescoço." },
      { term: "Veia Jugular", definition: "Principal veia que drena sangue da cabeça e pescoço." },
      { term: "Sístole", definition: "Contração do músculo cardíaco." },
      { term: "Diástole", definition: "Relaxamento do músculo cardíaco." },
      { term: "Nó Sinoatrial", definition: "Marcapasso natural do coração que gera impulsos elétricos." },
      {
        term: "Nó Atrioventricular",
        definition: "Estrutura que retarda condução elétrica entre átrios e ventrículos.",
      },
      { term: "Septo Interventricular", definition: "Parede que separa os ventrículos direito e esquerdo." },
      { term: "Septo Interatrial", definition: "Parede que separa os átrios direito e esquerdo." },
      { term: "Valva Mitral", definition: "Valva bicúspide entre átrio e ventrículo esquerdos." },
      { term: "Valva Tricúspide", definition: "Valva entre átrio e ventrículo direitos." },
      { term: "Valva Aórtica", definition: "Valva semilunar na saída do ventrículo esquerdo." },
      { term: "Valva Pulmonar", definition: "Valva semilunar na saída do ventrículo direito." },
      { term: "Cordas Tendíneas", definition: "Estruturas que conectam valvas aos músculos papilares." },
      { term: "Músculo Papilar", definition: "Projeção muscular que ancora cordas tendíneas." },
      { term: "Seio Coronário", definition: "Veia que drena sangue do miocárdio para o átrio direito." },
      { term: "Artéria Coronária", definition: "Vaso que irriga o músculo cardíaco." },
      {
        term: "Arco Aórtico",
        definition: "Curvatura da aorta que dá origem a artérias para cabeça e membros superiores.",
      },
      { term: "Aorta Torácica", definition: "Segmento da aorta que percorre o tórax." },
      { term: "Aorta Abdominal", definition: "Segmento da aorta que percorre o abdome." },
      { term: "Artéria Celíaca", definition: "Primeiro ramo da aorta abdominal que irriga vísceras superiores." },
      {
        term: "Artéria Mesentérica Superior",
        definition: "Artéria que irriga intestino delgado e parte do intestino grosso.",
      },
      { term: "Artéria Mesentérica Inferior", definition: "Artéria que irriga parte distal do intestino grosso." },
      { term: "Artéria Renal", definition: "Artéria que irriga os rins." },
      { term: "Artéria Ilíaca", definition: "Ramo terminal da aorta que irriga pelve e membros inferiores." },
      { term: "Veia Porta", definition: "Veia que transporta sangue do trato digestivo ao fígado." },
      { term: "Sistema Porta-Hepático", definition: "Sistema venoso entre intestinos e fígado." },
      { term: "Veia Ázigos", definition: "Veia que drena parede torácica e abdome superior." },
      { term: "Veia Hemiázigos", definition: "Tributária da veia ázigos no lado esquerdo." },
      { term: "Anastomose", definition: "Conexão entre vasos sanguíneos ou nervos." },
      { term: "Vascularização", definition: "Suprimento sanguíneo de uma região ou órgão." },
      { term: "Angiologia", definition: "Estudo científico dos vasos sanguíneos e linfáticos." },
      { term: "Polígono de Willis", definition: "Rede arterial na base do cérebro que garante irrigação cerebral." },
      { term: "Seio Venoso", definition: "Canal venoso entre as camadas da dura-máter." },
      { term: "Seio Cavernoso", definition: "Espaço venoso na base do crânio." },
    ],
  },
  {
    category: "Sistema Respiratório",
    terms: [
      { term: "Faringe", definition: "Tubo muscular que conecta a cavidade nasal e oral ao esôfago e laringe." },
      { term: "Laringe", definition: "Órgão que contém as cordas vocais e conecta a faringe à traqueia." },
      { term: "Traqueia", definition: "Tubo cartilaginoso que conduz ar da laringe aos brônquios." },
      { term: "Brônquio", definition: "Ramificação da traqueia que conduz ar aos pulmões." },
      { term: "Alvéolo", definition: "Estrutura microscópica nos pulmões onde ocorre a troca gasosa." },
      { term: "Pleura", definition: "Membrana serosa que reveste os pulmões e a cavidade torácica." },
      { term: "Hematose", definition: "Troca gasosa entre sangue e ar nos pulmões." },
      { term: "Ventilação", definition: "Movimento de ar para dentro e fora dos pulmões." },
      { term: "Inspiração", definition: "Entrada de ar nos pulmões." },
      { term: "Expiração", definition: "Saída de ar dos pulmões." },
      { term: "Mediastino", definition: "Região central do tórax entre os pulmões." },
      { term: "Hilo Pulmonar", definition: "Região onde vasos e brônquios entram no pulmão." },
      { term: "Lobo Pulmonar", definition: "Divisão anatômica do pulmão separada por fissuras." },
      { term: "Segmento Broncopulmonar", definition: "Unidade funcional do pulmão irrigada por brônquio segmentar." },
      { term: "Carina", definition: "Ponto de bifurcação da traqueia em brônquios principais." },
    ],
  },
  {
    category: "Sistema Digestório",
    terms: [
      { term: "Esôfago", definition: "Tubo muscular que conduz alimento da faringe ao estômago." },
      { term: "Estômago", definition: "Órgão digestivo que armazena e digere alimentos." },
      { term: "Intestino Delgado", definition: "Segmento do tubo digestivo onde ocorre maior absorção de nutrientes." },
      { term: "Intestino Grosso", definition: "Segmento final do tubo digestivo que absorve água e forma fezes." },
      { term: "Fígado", definition: "Maior glândula do corpo, responsável por múltiplas funções metabólicas." },
      { term: "Vesícula Biliar", definition: "Órgão que armazena e concentra bile produzida pelo fígado." },
      { term: "Pâncreas", definition: "Glândula mista com funções endócrinas e exócrinas." },
      { term: "Baço", definition: "Órgão linfoide que filtra sangue e armazena células sanguíneas." },
      { term: "Peritônio", definition: "Membrana serosa que reveste a cavidade abdominal." },
      { term: "Mesentério", definition: "Dobra do peritônio que suspende órgãos abdominais." },
      { term: "Glândula Parótida", definition: "Maior glândula salivar localizada na face." },
    ],
  },
  {
    category: "Sistema Urinário",
    terms: [
      { term: "Rim", definition: "Órgão responsável pela filtração do sangue e produção de urina." },
      { term: "Ureter", definition: "Tubo que conduz urina do rim à bexiga." },
      { term: "Bexiga", definition: "Órgão que armazena urina antes da micção." },
      { term: "Uretra", definition: "Canal que conduz urina da bexiga para o exterior." },
      { term: "Néfron", definition: "Unidade funcional do rim responsável pela filtração." },
      { term: "Glomérulo", definition: "Rede de capilares no néfron onde ocorre filtração." },
      { term: "Cápsula de Bowman", definition: "Estrutura que envolve o glomérulo e coleta o filtrado." },
      { term: "Túbulo Renal", definition: "Estrutura tubular do néfron onde ocorre reabsorção e secreção." },
      { term: "Pelve Renal", definition: "Estrutura em forma de funil que coleta urina no rim." },
      { term: "Hilo Renal", definition: "Região côncava do rim por onde entram e saem vasos e ureter." },
      { term: "Córtex Renal", definition: "Camada externa do rim contendo corpúsculos renais." },
      { term: "Medula Renal", definition: "Camada interna do rim contendo pirâmides renais." },
    ],
  },
  {
    category: "Sistema Genital",
    terms: [
      { term: "Testículo", definition: "Gônada masculina que produz espermatozoides e hormônios." },
      { term: "Epidídimo", definition: "Estrutura onde espermatozoides amadurecem e são armazenados." },
      { term: "Ducto Deferente", definition: "Canal que transporta espermatozoides do epidídimo." },
      { term: "Próstata", definition: "Glândula masculina que produz parte do líquido seminal." },
      { term: "Vesícula Seminal", definition: "Glândula que produz secreção nutritiva para espermatozoides." },
      { term: "Ovário", definition: "Gônada feminina que produz óvulos e hormônios." },
      { term: "Tuba Uterina", definition: "Canal que conduz óvulo do ovário ao útero." },
      { term: "Útero", definition: "Órgão muscular onde ocorre desenvolvimento fetal." },
      { term: "Endométrio", definition: "Camada interna do útero que se renova ciclicamente." },
      { term: "Miométrio", definition: "Camada muscular do útero responsável por contrações." },
      { term: "Vagina", definition: "Canal muscular que conecta útero ao exterior." },
      { term: "Vulva", definition: "Conjunto de estruturas genitais externas femininas." },
      { term: "Glândula Mamária", definition: "Glândula modificada que produz leite." },
    ],
  },
  {
    category: "Sistema Nervoso",
    terms: [
      {
        term: "Nervo",
        definition: "Estrutura que transmite impulsos elétricos entre o sistema nervoso central e o corpo.",
      },
      { term: "Medula Espinal", definition: "Estrutura nervosa que se estende da base do crânio até a região lombar." },
      { term: "Cone Medular", definition: "Extremidade inferior afilada da medula espinal." },
      { term: "Cauda Equina", definition: "Conjunto de raízes nervosas que se estendem abaixo do cone medular." },
      { term: "Plexo", definition: "Rede de nervos ou vasos sanguíneos entrelaçados." },
      { term: "Dermátomo", definition: "Área da pele inervada por um único nervo espinal." },
      { term: "Inervação", definition: "Suprimento nervoso de uma região ou órgão." },
      { term: "Sistema Nervoso Central", definition: "Composto por encéfalo e medula espinal." },
      { term: "Sistema Nervoso Periférico", definition: "Composto por nervos e gânglios fora do SNC." },
      { term: "Neurônio", definition: "Célula nervosa especializada na transmissão de impulsos." },
      { term: "Sinapse", definition: "Junção entre dois neurônios onde ocorre transmissão de sinais." },
      { term: "Gânglio", definition: "Agrupamento de corpos celulares de neurônios fora do SNC." },
      { term: "Raiz Dorsal", definition: "Raiz sensitiva de um nervo espinal." },
      { term: "Raiz Ventral", definition: "Raiz motora de um nervo espinal." },
      { term: "Substância Branca", definition: "Tecido nervoso composto principalmente por axônios mielinizados." },
      { term: "Substância Cinzenta", definition: "Tecido nervoso composto principalmente por corpos celulares." },
      { term: "Encéfalo", definition: "Parte do sistema nervoso central contida no crânio." },
      { term: "Cérebro", definition: "Maior parte do encéfalo responsável por funções superiores." },
      { term: "Cerebelo", definition: "Parte do encéfalo responsável por coordenação e equilíbrio." },
      { term: "Tronco Encefálico", definition: "Estrutura que conecta cérebro e medula espinal." },
      { term: "Meninges", definition: "Membranas que envolvem e protegem o sistema nervoso central." },
      { term: "Dura-máter", definition: "Meninge mais externa e resistente." },
      { term: "Aracnoide", definition: "Meninge intermediária com aspecto de teia de aranha." },
      { term: "Pia-máter", definition: "Meninge mais interna e delicada, aderida ao tecido nervoso." },
      {
        term: "Líquido Cefalorraquidiano",
        definition: "Fluido que circula no sistema nervoso central, oferecendo proteção.",
      },
      { term: "Nervo Facial", definition: "Nervo craniano VII responsável pela expressão facial." },
      { term: "Nervo Trigêmeo", definition: "Nervo craniano V responsável pela sensibilidade da face." },
      { term: "Plexo Braquial", definition: "Rede de nervos que inerva membro superior." },
      { term: "Plexo Lombossacral", definition: "Rede de nervos que inerva membro inferior." },
      { term: "Nervo Frênico", definition: "Nervo que inerva o diafragma." },
      { term: "Nervo Vago", definition: "Nervo craniano X com ampla distribuição visceral." },
      { term: "Nervo Ciático", definition: "Maior nervo do corpo que inerva membro inferior." },
      { term: "Nervo Mediano", definition: "Nervo que inerva parte anterior do antebraço e mão." },
      { term: "Nervo Radial", definition: "Nervo que inerva músculos extensores do membro superior." },
      { term: "Nervo Ulnar", definition: "Nervo que inerva músculos intrínsecos da mão." },
      { term: "Nervo Femoral", definition: "Nervo que inerva músculos anteriores da coxa." },
      { term: "Nervo Tibial", definition: "Ramo do nervo ciático que inerva parte posterior da perna." },
      { term: "Nervo Fibular", definition: "Ramo do nervo ciático que inerva parte lateral da perna." },
      { term: "Gânglio Cervical Superior", definition: "Gânglio simpático no pescoço." },
      {
        term: "Gânglio Estrelado",
        definition: "Gânglio simpático formado pela fusão de gânglios cervical inferior e torácico.",
      },
      { term: "Cadeia Simpática", definition: "Série de gânglios simpáticos ao longo da coluna vertebral." },
      {
        term: "Sistema Nervoso Autônomo",
        definition: "Divisão do sistema nervoso que controla funções involuntárias.",
      },
      { term: "Sistema Simpático", definition: "Divisão do SNA que prepara corpo para situações de estresse." },
      { term: "Sistema Parassimpático", definition: "Divisão do SNA que promove repouso e digestão." },
      { term: "Acetilcolina", definition: "Neurotransmissor do sistema parassimpático." },
      { term: "Noradrenalina", definition: "Neurotransmissor do sistema simpático." },
      { term: "Reflexo", definition: "Resposta automática e involuntária a um estímulo." },
      { term: "Arco Reflexo", definition: "Via neural que medeia um reflexo." },
      { term: "Propriocepção", definition: "Percepção da posição e movimento do corpo no espaço." },
      { term: "Nocicepção", definition: "Percepção de estímulos dolorosos." },
      { term: "Somestesia", definition: "Sensibilidade corporal geral incluindo tato, temperatura e dor." },
      { term: "Neurologia", definition: "Estudo científico do sistema nervoso." },
    ],
  },
  {
    category: "Sistema Endócrino",
    terms: [
      { term: "Tireoide", definition: "Glândula endócrina que regula metabolismo." },
      { term: "Paratireoide", definition: "Glândulas que regulam níveis de cálcio no sangue." },
      { term: "Hipófise", definition: "Glândula mestra que controla outras glândulas endócrinas." },
      { term: "Suprarrenal", definition: "Glândula localizada sobre os rins que produz hormônios do estresse." },
    ],
  },
  {
    category: "Sistema Linfático",
    terms: [
      { term: "Linfonodo", definition: "Estrutura do sistema linfático que filtra a linfa." },
      { term: "Linfa", definition: "Fluido intersticial que circula no sistema linfático." },
      { term: "Ducto Torácico", definition: "Maior vaso linfático que drena linfa para o sistema venoso." },
      { term: "Timo", definition: "Órgão linfoide onde ocorre maturação de linfócitos T." },
      { term: "Amígdala", definition: "Tecido linfoide na faringe que participa da defesa imunológica." },
    ],
  },
  {
    category: "Estruturas Gerais",
    terms: [
      { term: "Hérnia", definition: "Protrusão de órgão ou tecido através de abertura anormal." },
      { term: "Canal Inguinal", definition: "Passagem na parede abdominal inferior." },
      { term: "Segmentação", definition: "Princípio de organização corporal em unidades repetidas." },
      { term: "Esplancnologia", definition: "Estudo científico das vísceras e órgãos internos." },
    ],
  },
]

// Manter compatibilidade com código existente
export const glossaryTerms = glossaryByCategory
  .flatMap((category) => category.terms)
  .sort((a, b) => a.term.localeCompare(b.term))
