export interface GlossaryTerm {
  term: string
  definition: string
}

export interface GlossaryCategory {
  category: string
  terms: GlossaryTerm[]
}

export const glossaryByCategory: GlossaryCategory[] = [
  {
    category: "Terminologia Anatômica",
    terms: [
      { term: "Anatomia", definition: "Ciência que estuda a estrutura do corpo humano e suas partes." },
      { term: "Anterior", definition: "Posição na frente do corpo ou de uma estrutura." },
      { term: "Posterior", definition: "Posição atrás do corpo ou de uma estrutura." },
      { term: "Medial", definition: "Mais próximo da linha média do corpo." },
      { term: "Lateral", definition: "Mais afastado da linha média do corpo." },
      { term: "Proximal", definition: "Mais próximo do ponto de origem ou do tronco." },
      { term: "Distal", definition: "Mais afastado do ponto de origem ou do tronco." },
      { term: "Superior", definition: "Acima ou em direção à cabeça." },
      { term: "Inferior", definition: "Abaixo ou em direção aos pés." },
      { term: "Superficial", definition: "Mais próximo da superfície do corpo." },
      { term: "Profundo", definition: "Mais afastado da superfície do corpo." },
      { term: "Ventral", definition: "Relativo à parte anterior do corpo." },
      { term: "Dorsal", definition: "Relativo à parte posterior do corpo." },
      { term: "Cranial", definition: "Em direção à cabeça." },
      { term: "Caudal", definition: "Em direção à cauda ou extremidade inferior." },
      { term: "Ipsilateral", definition: "Do mesmo lado do corpo." },
      { term: "Contralateral", definition: "Do lado oposto do corpo." },
      { term: "Plano Sagital", definition: "Plano vertical que divide o corpo em partes direita e esquerda." },
      { term: "Plano Coronal", definition: "Plano vertical que divide o corpo em partes anterior e posterior." },
      { term: "Plano Transversal", definition: "Plano horizontal que divide o corpo em partes superior e inferior." },
      { term: "Posição Anatômica", definition: "Posição de referência com corpo ereto, face voltada para frente, braços ao lado do corpo com palmas para frente." },
      { term: "Eixo Longitudinal", definition: "Eixo que percorre o corpo de cima para baixo." },
      { term: "Eixo Transversal", definition: "Eixo que percorre o corpo de lado a lado." },
      { term: "Eixo Anteroposterior", definition: "Eixo que percorre o corpo da frente para trás." },
      { term: "Bilateral", definition: "Presente ou ocorrendo em ambos os lados do corpo." },
      { term: "Unilateral", definition: "Presente ou ocorrendo em apenas um lado do corpo." },
      { term: "Axial", definition: "Relativo ao eixo central do corpo." },
      { term: "Apendicular", definition: "Relativo aos membros ou apêndices do corpo." },
      { term: "Somático", definition: "Relativo à parede corporal ou estruturas voluntárias." },
      { term: "Visceral", definition: "Relativo aos órgãos internos." },
      { term: "Parietal", definition: "Relativo à parede de uma cavidade ou estrutura." },
    ],
  },
  {
    category: "Sistema Esquelético",
    terms: [
      {
        term: "Esqueleto Axial",
        definition: "Parte do esqueleto formada por crânio, coluna vertebral e caixa torácica.",
      },
      {
        term: "Esqueleto Apendicular",
        definition: "Parte do esqueleto formada pelos membros superiores e inferiores.",
      },
      { term: "Vértebra", definition: "Osso individual que compõe a coluna vertebral." },
      { term: "Forame", definition: "Abertura ou orifício em um osso por onde passam nervos e vasos." },
      { term: "Sutura", definition: "Articulação fibrosa imóvel entre ossos do crânio." },
      { term: "Crânio", definition: "Estrutura óssea que protege o encéfalo e forma a cabeça." },
      { term: "Neurocrânio", definition: "Parte do crânio que envolve e protege o encéfalo." },
      { term: "Viscerocrânio", definition: "Parte do crânio que forma a face e estruturas relacionadas." },
      { term: "Mandíbula", definition: "Osso móvel da face que forma a arcada dentária inferior." },
      { term: "Maxila", definition: "Osso da face que forma a arcada dentária superior." },
      { term: "Costela", definition: "Osso curvo que forma a caixa torácica." },
      { term: "Esterno", definition: "Osso plano central da caixa torácica." },
      { term: "Osteologia", definition: "Estudo científico dos ossos e do sistema esquelético." },
      { term: "Osso Longo", definition: "Osso com comprimento maior que largura, encontrado nos membros." },
      { term: "Osso Curto", definition: "Osso com dimensões aproximadamente iguais, como os do carpo." },
      { term: "Osso Plano", definition: "Osso achatado como escápula, ossos do crânio e esterno." },
      { term: "Osso Irregular", definition: "Osso com forma complexa como vértebras e ossos da face." },
      { term: "Osso Sesamoide", definition: "Osso pequeno dentro de tendões, como a patela." },
      { term: "Diáfise", definition: "Haste ou corpo principal de um osso longo." },
      { term: "Epífise", definition: "Extremidade de um osso longo." },
      { term: "Metáfise", definition: "Região entre diáfise e epífise onde ocorre crescimento ósseo." },
      { term: "Periósteo", definition: "Membrana fibrosa que reveste externamente os ossos." },
      { term: "Endósteo", definition: "Membrana que reveste a cavidade medular dos ossos." },
      { term: "Medula Óssea Vermelha", definition: "Tecido hematopoiético que produz células sanguíneas." },
      { term: "Medula Óssea Amarela", definition: "Tecido adiposo presente na cavidade medular de ossos longos." },
      { term: "Osso Compacto", definition: "Tecido ósseo denso na camada externa dos ossos." },
      { term: "Osso Esponjoso", definition: "Tecido ósseo poroso nas epífises e no interior de ossos chatos." },
      { term: "Clavícula", definition: "Osso que conecta o esterno ao ombro." },
      { term: "Escápula", definition: "Osso plano do ombro que articula com úmero e clavícula." },
      { term: "Úmero", definition: "Osso do braço entre ombro e cotovelo." },
      { term: "Rádio", definition: "Osso lateral do antebraço." },
      { term: "Ulna", definition: "Osso medial do antebraço." },
      { term: "Carpo", definition: "Conjunto de oito ossos que formam o punho." },
      { term: "Metacarpo", definition: "Ossos da palma da mão." },
      { term: "Falange", definition: "Ossos dos dedos das mãos e pés." },
      { term: "Pelve", definition: "Estrutura óssea formada pelos ossos do quadril e sacro." },
      { term: "Ílio", definition: "Porção superior do osso do quadril." },
      { term: "Ísquio", definition: "Porção inferior e posterior do osso do quadril." },
      { term: "Púbis", definition: "Porção anterior e inferior do osso do quadril." },
      { term: "Fêmur", definition: "Osso da coxa, o mais longo e forte do corpo." },
      { term: "Patela", definition: "Osso sesamoide do joelho." },
      { term: "Tíbia", definition: "Osso medial e mais forte da perna." },
      { term: "Fíbula", definition: "Osso lateral e mais fino da perna." },
      { term: "Tarso", definition: "Conjunto de ossos que formam o tornozelo." },
      { term: "Metatarso", definition: "Ossos do mediopé." },
      { term: "Calcâneo", definition: "Maior osso do tarso, forma o calcanhar." },
      { term: "Sacro", definition: "Osso formado pela fusão de cinco vértebras sacrais." },
      { term: "Cóccix", definition: "Osso terminal da coluna vertebral." },
      { term: "Atlas", definition: "Primeira vértebra cervical que sustenta o crânio." },
      { term: "Áxis", definition: "Segunda vértebra cervical com processo odontoide." },
      { term: "Vértebra Cervical", definition: "Uma das sete vértebras do pescoço." },
      { term: "Vértebra Torácica", definition: "Uma das doze vértebras que articulam com costelas." },
      { term: "Vértebra Lombar", definition: "Uma das cinco vértebras da região inferior das costas." },
      { term: "Processo Espinhoso", definition: "Projeção posterior de uma vértebra." },
      { term: "Processo Transverso", definition: "Projeção lateral de uma vértebra." },
      { term: "Corpo Vertebral", definition: "Parte anterior e cilíndrica de uma vértebra." },
      { term: "Canal Vertebral", definition: "Espaço dentro da coluna vertebral que contém a medula espinal." },
      { term: "Forame Intervertebral", definition: "Abertura entre vértebras por onde passam nervos espinais." },
      { term: "Disco Intervertebral", definition: "Estrutura fibrocartilaginosa entre vértebras adjacentes." },
      { term: "Núcleo Pulposo", definition: "Centro gelatinoso do disco intervertebral." },
      { term: "Anel Fibroso", definition: "Camada externa fibrosa do disco intervertebral." },
      { term: "Cifose", definition: "Curvatura convexa posterior da coluna (região torácica)." },
      { term: "Lordose", definition: "Curvatura côncava posterior da coluna (regiões cervical e lombar)." },
      { term: "Escoliose", definition: "Curvatura lateral anormal da coluna vertebral." },
      { term: "Osso Frontal", definition: "Osso que forma a testa e parte superior das órbitas." },
      { term: "Osso Parietal", definition: "Osso da abóbada craniana, em número de dois." },
      { term: "Osso Temporal", definition: "Osso lateral do crânio que contém estruturas da audição." },
      { term: "Osso Occipital", definition: "Osso posterior do crânio com forame magno." },
      { term: "Osso Esfenoide", definition: "Osso em forma de borboleta na base do crânio." },
      { term: "Osso Etmoide", definition: "Osso na base do crânio que forma parte da cavidade nasal." },
      { term: "Órbita", definition: "Cavidade óssea que contém o globo ocular." },
      { term: "Seio Paranasal", definition: "Cavidade aérea nos ossos do crânio." },
      { term: "Forame Magno", definition: "Grande abertura no osso occipital por onde passa a medula espinal." },
      { term: "Sela Túrcica", definition: "Depressão do osso esfenoide que abriga a hipófise." },
      { term: "Processo Mastoide", definition: "Projeção do osso temporal onde se inserem músculos do pescoço." },
    ],
  },
  {
    category: "Sistema Articular",
    terms: [
      { term: "Articulação", definition: "Ponto de conexão entre dois ou mais ossos." },
      { term: "Ligamento", definition: "Tecido conjuntivo fibroso que conecta ossos entre si." },
      { term: "ATM", definition: "Articulação Temporomandibular - articulação entre mandíbula e crânio." },
      { term: "Sinartrose", definition: "Articulação fibrosa com pouco ou nenhum movimento." },
      { term: "Anfiartrose", definition: "Articulação cartilaginosa com movimento limitado." },
      { term: "Diartrose", definition: "Articulação sinovial com ampla mobilidade." },
      { term: "Cápsula Articular", definition: "Estrutura fibrosa que envolve articulações sinoviais." },
      { term: "Líquido Sinovial", definition: "Fluido lubrificante presente em articulações móveis." },
      { term: "Cartilagem Articular", definition: "Tecido que reveste superfícies ósseas em articulações." },
      { term: "Menisco", definition: "Estrutura fibrocartilaginosa em algumas articulações como o joelho." },
      { term: "Bursa", definition: "Bolsa sinovial que reduz atrito entre estruturas." },
      { term: "Artrologia", definition: "Estudo científico das articulações e suas estruturas." },
      { term: "Membrana Sinovial", definition: "Camada interna da cápsula articular que produz líquido sinovial." },
      { term: "Articulação Plana", definition: "Articulação sinovial com movimentos deslizantes limitados." },
      { term: "Articulação em Dobradiça", definition: "Articulação sinovial que permite flexão e extensão." },
      { term: "Articulação em Pivô", definition: "Articulação sinovial que permite rotação." },
      { term: "Articulação Condilar", definition: "Articulação sinovial com movimentos em dois planos." },
      { term: "Articulação em Sela", definition: "Articulação sinovial com movimentos em dois planos perpendiculares." },
      { term: "Articulação Esferóide", definition: "Articulação sinovial com movimento em todos os planos." },
      { term: "Sínfise", definition: "Articulação cartilaginosa com disco fibrocartilaginoso." },
      { term: "Sincondrose", definition: "Articulação cartilaginosa temporária com cartilagem hialina." },
      { term: "Articulação do Ombro", definition: "Articulação esferóide entre escápula e úmero." },
      { term: "Articulação do Cotovelo", definition: "Articulação em dobradiça entre úmero, rádio e ulna." },
      { term: "Articulação do Punho", definition: "Articulação entre rádio, ulna e ossos do carpo." },
      { term: "Articulação do Quadril", definition: "Articulação esferóide entre pelve e fêmur." },
      { term: "Articulação do Joelho", definition: "Maior articulação do corpo, entre fêmur e tíbia." },
      { term: "Articulação do Tornozelo", definition: "Articulação em dobradiça entre tíbia, fíbula e tálus." },
      { term: "Ligamento Cruzado Anterior", definition: "Ligamento que estabiliza o joelho anteriormente." },
      { term: "Ligamento Cruzado Posterior", definition: "Ligamento que estabiliza o joelho posteriormente." },
      { term: "Ligamento Colateral Medial", definition: "Ligamento na parte medial do joelho." },
      { term: "Ligamento Colateral Lateral", definition: "Ligamento na parte lateral do joelho." },
      { term: "Manguito Rotador", definition: "Grupo de músculos e tendões que estabilizam o ombro." },
      { term: "Ligamento Inguinal", definition: "Ligamento que forma a base do canal inguinal." },
      { term: "Disco Articular", definition: "Estrutura fibrocartilaginosa que divide algumas articulações." },
      { term: "Lábio Articular", definition: "Anel de fibrocartilagem que aprofunda cavidades articulares." },
      { term: "Artrite", definition: "Inflamação de uma articulação." },
      { term: "Artrose", definition: "Degeneração da cartilagem articular." },
      { term: "Luxação", definition: "Deslocamento dos ossos de uma articulação." },
      { term: "Entorse", definition: "Lesão dos ligamentos de uma articulação." },
    ],
  },
  {
    category: "Sistema Muscular",
    terms: [
      { term: "Músculo", definition: "Tecido contrátil responsável pelo movimento do corpo." },
      { term: "Tendão", definition: "Tecido conjuntivo fibroso que conecta músculos aos ossos." },
      { term: "Origem Muscular", definition: "Ponto de fixação proximal e menos móvel de um músculo." },
      { term: "Inserção Muscular", definition: "Ponto de fixação distal e mais móvel de um músculo." },
      { term: "Agonista", definition: "Músculo principal responsável por um movimento específico." },
      { term: "Antagonista", definition: "Músculo que se opõe à ação do agonista." },
      { term: "Sinergista", definition: "Músculo que auxilia o agonista em um movimento." },
      { term: "Fáscia", definition: "Camada de tecido conjuntivo que envolve músculos e órgãos." },
      { term: "Aponeurose", definition: "Lâmina tendinosa plana que conecta músculos." },
      { term: "Diafragma", definition: "Músculo principal da respiração que separa tórax e abdome." },
      {
        term: "Músculo Esternocleidomastóideo",
        definition: "Músculo do pescoço que permite rotação e flexão da cabeça.",
      },
      { term: "Miologia", definition: "Estudo científico dos músculos e suas funções." },
      { term: "Miótomo", definition: "Músculos inervados por um único nervo espinal." },
      { term: "Músculo Estriado Esquelético", definition: "Músculo voluntário ligado ao esqueleto." },
      { term: "Músculo Liso", definition: "Músculo involuntário encontrado em órgãos internos." },
      { term: "Músculo Cardíaco", definition: "Músculo estriado involuntário exclusivo do coração." },
      { term: "Fibra Muscular", definition: "Célula muscular alongada e contrátil." },
      { term: "Sarcômero", definition: "Unidade contrátil básica do músculo estriado." },
      { term: "Actina", definition: "Proteína contrátil fina do músculo." },
      { term: "Miosina", definition: "Proteína contrátil espessa do músculo." },
      { term: "Placa Motora", definition: "Sinapse entre neurônio motor e fibra muscular." },
      { term: "Unidade Motora", definition: "Neurônio motor e todas as fibras musculares que inerva." },
      { term: "Tônus Muscular", definition: "Contração parcial contínua dos músculos em repouso." },
      { term: "Contração Isotônica", definition: "Contração muscular com mudança de comprimento." },
      { term: "Contração Isométrica", definition: "Contração muscular sem mudança de comprimento." },
      { term: "Tetania", definition: "Contração muscular sustentada." },
      { term: "Fadiga Muscular", definition: "Diminuição da capacidade contrátil por uso prolongado." },
      { term: "Hipertrofia Muscular", definition: "Aumento do tamanho das fibras musculares." },
      { term: "Atrofia Muscular", definition: "Diminuição do tamanho muscular por desuso ou doença." },
      { term: "Músculo Trapézio", definition: "Grande músculo superficial das costas e pescoço." },
      { term: "Músculo Deltóide", definition: "Músculo do ombro responsável por abdução do braço." },
      { term: "Músculo Peitoral Maior", definition: "Músculo anterior do tórax que move o braço." },
      { term: "Músculo Grande Dorsal", definition: "Maior músculo das costas que estende e aduz o braço." },
      { term: "Músculo Bíceps Braquial", definition: "Músculo anterior do braço que flexiona cotovelo." },
      { term: "Músculo Tríceps Braquial", definition: "Músculo posterior do braço que estende cotovelo." },
      { term: "Músculos do Antebraço", definition: "Músculos que controlam movimentos do punho e dedos." },
      { term: "Músculos Intercostais", definition: "Músculos entre as costelas que auxiliam a respiração." },
      { term: "Músculo Reto Abdominal", definition: "Músculo anterior do abdome que flexiona o tronco." },
      { term: "Músculos Oblíquos", definition: "Músculos laterais do abdome que rotacionam o tronco." },
      { term: "Músculo Transverso do Abdome", definition: "Músculo abdominal profundo que comprime vísceras." },
      { term: "Músculo Quadríceps Femoral", definition: "Grupo de quatro músculos anteriores da coxa que estendem joelho." },
      { term: "Músculo Reto Femoral", definition: "Parte do quadríceps que também flexiona o quadril." },
      { term: "Músculo Vasto Lateral", definition: "Parte lateral do quadríceps femoral." },
      { term: "Músculo Vasto Medial", definition: "Parte medial do quadríceps femoral." },
      { term: "Músculo Vasto Intermédio", definition: "Parte profunda do quadríceps femoral." },
      { term: "Músculos Isquiotibiais", definition: "Grupo de músculos posteriores da coxa que flexionam joelho." },
      { term: "Músculo Bíceps Femoral", definition: "Músculo isquiotibial lateral." },
      { term: "Músculo Semitendíneo", definition: "Músculo isquiotibial medial." },
      { term: "Músculo Semimembranáceo", definition: "Músculo isquiotibial profundo e medial." },
      { term: "Músculo Gastrocnêmio", definition: "Músculo superficial da panturrilha." },
      { term: "Músculo Sóleo", definition: "Músculo profundo da panturrilha." },
      { term: "Tendão Calcâneo", definition: "Tendão de Aquiles que conecta panturrilha ao calcanhar." },
      { term: "Músculo Tibial Anterior", definition: "Músculo anterior da perna que faz dorsiflexão do pé." },
      { term: "Músculos Glúteos", definition: "Músculos da região das nádegas." },
      { term: "Músculo Glúteo Máximo", definition: "Maior músculo do corpo, principal extensor do quadril." },
      { term: "Músculo Glúteo Médio", definition: "Músculo abdutor do quadril." },
      { term: "Músculo Glúteo Mínimo", definition: "Menor músculo glúteo, também abdutor." },
      { term: "Músculo Iliopsoas", definition: "Principal flexor do quadril." },
      { term: "Músculo Piriforme", definition: "Músculo profundo do quadril, rotador lateral." },
      { term: "Músculos da Expressão Facial", definition: "Músculos que movem a pele da face." },
      { term: "Músculo Orbicular do Olho", definition: "Músculo que fecha as pálpebras." },
      { term: "Músculo Orbicular da Boca", definition: "Músculo que fecha e projeta os lábios." },
      { term: "Músculos da Mastigação", definition: "Músculos que movem a mandíbula." },
      { term: "Músculo Masseter", definition: "Principal músculo elevador da mandíbula." },
      { term: "Músculo Temporal", definition: "Músculo que eleva e retrai a mandíbula." },
      { term: "Assoalho Pélvico", definition: "Grupo de músculos que suporta órgãos pélvicos." },
      { term: "Períneo", definition: "Região entre ânus e órgãos genitais com músculos de suporte." },
    ],
  },
  {
    category: "Movimentos Articulares",
    terms: [
      { term: "Flexão", definition: "Movimento que diminui o ângulo entre duas partes do corpo." },
      { term: "Extensão", definition: "Movimento que aumenta o ângulo entre duas partes do corpo." },
      { term: "Abdução", definition: "Movimento de afastamento da linha média do corpo." },
      { term: "Adução", definition: "Movimento de aproximação em direção à linha média do corpo." },
      { term: "Rotação", definition: "Movimento circular ao redor de um eixo." },
      { term: "Circundução", definition: "Movimento circular combinando flexão, extensão, abdução e adução." },
      { term: "Pronação", definition: "Rotação do antebraço que posiciona a palma para baixo." },
      { term: "Supinação", definition: "Rotação do antebraço que posiciona a palma para cima." },
      { term: "Inversão", definition: "Movimento da planta do pé em direção à linha média." },
      { term: "Eversão", definition: "Movimento da planta do pé para fora da linha média." },
      { term: "Dorsiflexão", definition: "Movimento que aproxima o dorso do pé da perna." },
      { term: "Flexão Plantar", definition: "Movimento que afasta o dorso do pé da perna." },
      { term: "Protração", definition: "Movimento anterior de uma estrutura, como a mandíbula." },
      { term: "Retração", definition: "Movimento posterior de uma estrutura." },
      { term: "Elevação", definition: "Movimento superior de uma estrutura, como os ombros." },
      { term: "Depressão", definition: "Movimento inferior de uma estrutura." },
      { term: "Oposição", definition: "Movimento do polegar em direção aos outros dedos." },
      { term: "Reposição", definition: "Retorno do polegar à posição anatômica." },
      { term: "Rotação Medial", definition: "Rotação em direção à linha média do corpo." },
      { term: "Rotação Lateral", definition: "Rotação para longe da linha média do corpo." },
      { term: "Flexão Lateral", definition: "Inclinação lateral do tronco ou pescoço." },
      { term: "Hiperextensão", definition: "Extensão além da posição anatômica." },
      { term: "Desvio Radial", definition: "Movimento lateral do punho em direção ao polegar." },
      { term: "Desvio Ulnar", definition: "Movimento lateral do punho em direção ao dedo mínimo." },
    ],
  },
  {
    category: "Sistema Cardiovascular",
    terms: [
      { term: "Coração", definition: "Órgão muscular que bombeia sangue pelo corpo." },
      { term: "Átrio", definition: "Câmara superior do coração que recebe sangue." },
      { term: "Ventrículo", definition: "Câmara inferior do coração que bombeia sangue." },
      { term: "Valva", definition: "Estrutura que controla o fluxo sanguíneo no coração." },
      { term: "Pericárdio", definition: "Membrana que envolve e protege o coração." },
      { term: "Miocárdio", definition: "Camada muscular do coração responsável pela contração." },
      { term: "Endocárdio", definition: "Camada interna que reveste as câmaras cardíacas." },
      { term: "Epicárdio", definition: "Camada externa do coração, parte visceral do pericárdio." },
      { term: "Artéria", definition: "Vaso sanguíneo que transporta sangue do coração para os tecidos." },
      { term: "Veia", definition: "Vaso sanguíneo que transporta sangue dos tecidos para o coração." },
      { term: "Capilar", definition: "Vaso sanguíneo microscópico onde ocorrem as trocas gasosas e de nutrientes." },
      { term: "Aorta", definition: "Maior artéria do corpo que se origina do ventrículo esquerdo." },
      { term: "Veia Cava", definition: "Grande veia que retorna sangue ao átrio direito." },
      { term: "Artéria Pulmonar", definition: "Vaso que transporta sangue do coração aos pulmões." },
      { term: "Veia Pulmonar", definition: "Vaso que retorna sangue oxigenado dos pulmões ao coração." },
      { term: "Artéria Carótida", definition: "Principal artéria que irriga cabeça e pescoço." },
      { term: "Veia Jugular", definition: "Principal veia que drena sangue da cabeça e pescoço." },
      { term: "Sístole", definition: "Contração do músculo cardíaco." },
      { term: "Diástole", definition: "Relaxamento do músculo cardíaco." },
      { term: "Nó Sinoatrial", definition: "Marcapasso natural do coração que gera impulsos elétricos." },
      {
        term: "Nó Atrioventricular",
        definition: "Estrutura que retarda condução elétrica entre átrios e ventrículos.",
      },
      { term: "Septo Interventricular", definition: "Parede que separa os ventrículos direito e esquerdo." },
      { term: "Septo Interatrial", definition: "Parede que separa os átrios direito e esquerdo." },
      { term: "Valva Mitral", definition: "Valva bicúspide entre átrio e ventrículo esquerdos." },
      { term: "Valva Tricúspide", definition: "Valva entre átrio e ventrículo direitos." },
      { term: "Valva Aórtica", definition: "Valva semilunar na saída do ventrículo esquerdo." },
      { term: "Valva Pulmonar", definition: "Valva semilunar na saída do ventrículo direito." },
      { term: "Cordas Tendíneas", definition: "Estruturas que conectam valvas aos músculos papilares." },
      { term: "Músculo Papilar", definition: "Projeção muscular que ancora cordas tendíneas." },
      { term: "Seio Coronário", definition: "Veia que drena sangue do miocárdio para o átrio direito." },
      { term: "Artéria Coronária", definition: "Vaso que irriga o músculo cardíaco." },
      {
        term: "Arco Aórtico",
        definition: "Curvatura da aorta que dá origem a artérias para cabeça e membros superiores.",
      },
      { term: "Aorta Torácica", definition: "Segmento da aorta que percorre o tórax." },
      { term: "Aorta Abdominal", definition: "Segmento da aorta que percorre o abdome." },
      { term: "Artéria Celíaca", definition: "Primeiro ramo da aorta abdominal que irriga vísceras superiores." },
      {
        term: "Artéria Mesentérica Superior",
        definition: "Artéria que irriga intestino delgado e parte do intestino grosso.",
      },
      { term: "Artéria Mesentérica Inferior", definition: "Artéria que irriga parte distal do intestino grosso." },
      { term: "Artéria Renal", definition: "Artéria que irriga os rins." },
      { term: "Artéria Ilíaca", definition: "Ramo terminal da aorta que irriga pelve e membros inferiores." },
      { term: "Veia Porta", definition: "Veia que transporta sangue do trato digestivo ao fígado." },
      { term: "Sistema Porta-Hepático", definition: "Sistema venoso entre intestinos e fígado." },
      { term: "Veia Ázigos", definition: "Veia que drena parede torácica e abdome superior." },
      { term: "Veia Hemiázigos", definition: "Tributária da veia ázigos no lado esquerdo." },
      { term: "Anastomose", definition: "Conexão entre vasos sanguíneos ou nervos." },
      { term: "Vascularização", definition: "Suprimento sanguíneo de uma região ou órgão." },
      { term: "Angiologia", definition: "Estudo científico dos vasos sanguíneos e linfáticos." },
      { term: "Polígono de Willis", definition: "Rede arterial na base do cérebro que garante irrigação cerebral." },
      { term: "Seio Venoso", definition: "Canal venoso entre as camadas da dura-máter." },
      { term: "Seio Cavernoso", definition: "Espaço venoso na base do crânio." },
      { term: "Circulação Sistêmica", definition: "Circulação do sangue do coração para o corpo e de volta." },
      { term: "Circulação Pulmonar", definition: "Circulação do sangue entre coração e pulmões." },
      { term: "Ciclo Cardíaco", definition: "Sequência completa de eventos durante um batimento cardíaco." },
      { term: "Débito Cardíaco", definition: "Volume de sangue bombeado pelo coração por minuto." },
      { term: "Frequência Cardíaca", definition: "Número de batimentos cardíacos por minuto." },
      { term: "Volume Sistólico", definition: "Volume de sangue ejetado por batimento." },
      { term: "Pressão Arterial", definition: "Força exercida pelo sangue nas paredes das artérias." },
      { term: "Arteriosclerose", definition: "Endurecimento das artérias." },
      { term: "Aterosclerose", definition: "Acúmulo de placas nas artérias." },
      { term: "Trombose", definition: "Formação de coágulo dentro de vaso sanguíneo." },
      { term: "Embolia", definition: "Obstrução de vaso sanguíneo por êmbolo." },
      { term: "Isquemia", definition: "Redução do fluxo sanguíneo para um tecido." },
      { term: "Infarto", definition: "Morte de tecido por falta de irrigação sanguínea." },
      { term: "Artéria Braquial", definition: "Principal artéria do braço." },
      { term: "Artéria Radial", definition: "Artéria do antebraço, comum para verificar pulso." },
      { term: "Artéria Femoral", definition: "Principal artéria da coxa." },
      { term: "Artéria Poplítea", definition: "Artéria posterior do joelho." },
      { term: "Artéria Tibial", definition: "Artéria da perna." },
      { term: "Artéria Pediosa", definition: "Artéria do dorso do pé." },
      { term: "Veia Safena Magna", definition: "Maior veia superficial do membro inferior." },
      { term: "Veia Safena Parva", definition: "Veia superficial posterior da perna." },
      { term: "Veia Cefálica", definition: "Veia superficial lateral do membro superior." },
      { term: "Veia Basílica", definition: "Veia superficial medial do membro superior." },
      { term: "Sistema Linfático Cardiovascular", definition: "Rede de vasos que drena excesso de líquido dos tecidos." },
    ],
  },
  {
    category: "Sistema Respiratório",
    terms: [
      { term: "Nariz", definition: "Órgão que filtra, aquece e umidifica o ar inspirado." },
      { term: "Cavidade Nasal", definition: "Espaço interno do nariz dividido pelo septo nasal." },
      { term: "Septo Nasal", definition: "Estrutura que divide a cavidade nasal em duas partes." },
      { term: "Concha Nasal", definition: "Projeção óssea na parede lateral da cavidade nasal." },
      { term: "Seio Paranasal Respiratório", definition: "Cavidade aérea nos ossos do crânio conectada ao nariz." },
      { term: "Faringe", definition: "Tubo muscular que conecta a cavidade nasal e oral ao esôfago e laringe." },
      { term: "Nasofaringe", definition: "Parte superior da faringe atrás do nariz." },
      { term: "Orofaringe", definition: "Parte média da faringe atrás da boca." },
      { term: "Laringofaringe", definition: "Parte inferior da faringe que se conecta à laringe." },
      { term: "Laringe", definition: "Órgão que contém as cordas vocais e conecta a faringe à traqueia." },
      { term: "Epiglote", definition: "Cartilagem que cobre a laringe durante a deglutição." },
      { term: "Cartilagem Tireoide", definition: "Maior cartilagem da laringe, forma o pomo de Adão." },
      { term: "Cartilagem Cricóide", definition: "Cartilagem em forma de anel na base da laringe." },
      { term: "Cordas Vocais", definition: "Pregas de tecido na laringe que produzem som." },
      { term: "Glote", definition: "Abertura entre as cordas vocais." },
      { term: "Traqueia", definition: "Tubo cartilaginoso que conduz ar da laringe aos brônquios." },
      { term: "Brônquio", definition: "Ramificação da traqueia que conduz ar aos pulmões." },
      { term: "Brônquio Principal", definition: "Primeiro ramo da traqueia, um para cada pulmão." },
      { term: "Brônquio Lobar", definition: "Ramificação que supre cada lobo pulmonar." },
      { term: "Brônquio Segmentar", definition: "Ramificação que supre segmentos broncopulmonares." },
      { term: "Bronquíolo", definition: "Pequena ramificação dos brônquios." },
      { term: "Bronquíolo Terminal", definition: "Menor bronquíolo que se ramifica em bronquíolos respiratórios." },
      { term: "Bronquíolo Respiratório", definition: "Bronquíolo com alvéolos em suas paredes." },
      { term: "Ducto Alveolar", definition: "Passagem que leva aos sacos alveolares." },
      { term: "Saco Alveolar", definition: "Agrupamento de alvéolos." },
      { term: "Alvéolo", definition: "Estrutura microscópica nos pulmões onde ocorre a troca gasosa." },
      { term: "Surfactante Pulmonar", definition: "Substância que reduz tensão superficial nos alvéolos." },
      { term: "Pulmão Direito", definition: "Pulmão com três lobos." },
      { term: "Pulmão Esquerdo", definition: "Pulmão com dois lobos." },
      { term: "Lobo Superior", definition: "Lobo mais superior do pulmão." },
      { term: "Lobo Médio", definition: "Lobo presente apenas no pulmão direito." },
      { term: "Lobo Inferior", definition: "Lobo mais inferior do pulmão." },
      { term: "Fissura Horizontal", definition: "Fissura entre lobos superior e médio do pulmão direito." },
      { term: "Fissura Oblíqua", definition: "Fissura entre lobos superior e inferior." },
      { term: "Pleura", definition: "Membrana serosa que reveste os pulmões e a cavidade torácica." },
      { term: "Pleura Visceral", definition: "Camada da pleura aderida à superfície do pulmão." },
      { term: "Pleura Parietal", definition: "Camada da pleura aderida à parede torácica." },
      { term: "Cavidade Pleural", definition: "Espaço entre as pleuras visceral e parietal." },
      { term: "Líquido Pleural", definition: "Fluido que lubrifica a cavidade pleural." },
      { term: "Hematose", definition: "Troca gasosa entre sangue e ar nos pulmões." },
      { term: "Ventilação", definition: "Movimento de ar para dentro e fora dos pulmões." },
      { term: "Inspiração", definition: "Entrada de ar nos pulmões." },
      { term: "Expiração", definition: "Saída de ar dos pulmões." },
      { term: "Mediastino", definition: "Região central do tórax entre os pulmões." },
      { term: "Hilo Pulmonar", definition: "Região onde vasos e brônquios entram no pulmão." },
      { term: "Lobo Pulmonar", definition: "Divisão anatômica do pulmão separada por fissuras." },
      { term: "Segmento Broncopulmonar", definition: "Unidade funcional do pulmão irrigada por brônquio segmentar." },
      { term: "Carina", definition: "Ponto de bifurcação da traqueia em brônquios principais." },
      { term: "Ápice Pulmonar", definition: "Parte superior do pulmão." },
      { term: "Base Pulmonar", definition: "Parte inferior do pulmão que repousa sobre o diafragma." },
      { term: "Capacidade Vital", definition: "Volume máximo de ar que pode ser expirado após inspiração máxima." },
      { term: "Volume Corrente", definition: "Volume de ar inspirado ou expirado em respiração normal." },
      { term: "Volume Residual", definition: "Volume de ar que permanece nos pulmões após expiração máxima." },
      { term: "Capacidade Pulmonar Total", definition: "Volume total de ar que os pulmões podem conter." },
      { term: "Pneumonia", definition: "Inflamação do tecido pulmonar." },
      { term: "Atelectasia", definition: "Colapso parcial ou total do pulmão." },
      { term: "Enfisema", definition: "Destruição das paredes alveolares." },
      { term: "Asma", definition: "Doença com estreitamento reversível das vias aéreas." },
      { term: "DPOC", definition: "Doença Pulmonar Obstrutiva Crônica." },
      { term: "Pneumotórax", definition: "Presença de ar na cavidade pleural." },
      { term: "Derrame Pleural", definition: "Acúmulo anormal de líquido na cavidade pleural." },
    ],
  },
  {
    category: "Sistema Digestório",
    terms: [
      { term: "Boca", definition: "Cavidade inicial do sistema digestório onde ocorre mastigação." },
      { term: "Lábios", definition: "Estruturas musculares que formam a abertura da boca." },
      { term: "Dentes", definition: "Estruturas ósseas para mastigação." },
      { term: "Língua", definition: "Órgão muscular móvel para gustação e deglutição." },
      { term: "Papilas Gustativas", definition: "Estruturas da língua que contêm receptores de paladar." },
      { term: "Palato Duro", definition: "Parte anterior óssea do céu da boca." },
      { term: "Palato Mole", definition: "Parte posterior muscular do céu da boca." },
      { term: "Úvula", definition: "Projeção do palato mole que pende na parte posterior da boca." },
      { term: "Glândula Salivar", definition: "Glândula que produz saliva." },
      { term: "Glândula Parótida", definition: "Maior glândula salivar localizada na face." },
      { term: "Glândula Submandibular", definition: "Glândula salivar sob a mandíbula." },
      { term: "Glândula Sublingual", definition: "Menor glândula salivar sob a língua." },
      { term: "Esôfago", definition: "Tubo muscular que conduz alimento da faringe ao estômago." },
      { term: "Esfíncter Esofágico Superior", definition: "Músculo que controla entrada no esôfago." },
      { term: "Esfíncter Esofágico Inferior", definition: "Músculo que controla passagem do esôfago ao estômago." },
      { term: "Estômago", definition: "Órgão digestivo que armazena e digere alimentos." },
      { term: "Cárdia", definition: "Região do estômago próxima à junção com esôfago." },
      { term: "Fundo Gástrico", definition: "Parte superior do estômago." },
      { term: "Corpo Gástrico", definition: "Parte central e maior do estômago." },
      { term: "Antro Pilórico", definition: "Parte inferior do estômago próxima ao piloro." },
      { term: "Piloro", definition: "Abertura entre estômago e duodeno." },
      { term: "Esfíncter Pilórico", definition: "Músculo que controla passagem do estômago ao intestino." },
      { term: "Curvatura Maior", definition: "Borda lateral convexa do estômago." },
      { term: "Curvatura Menor", definition: "Borda medial côncava do estômago." },
      { term: "Mucosa Gástrica", definition: "Revestimento interno do estômago." },
      { term: "Intestino Delgado", definition: "Segmento do tubo digestivo onde ocorre maior absorção de nutrientes." },
      { term: "Duodeno", definition: "Primeira porção do intestino delgado." },
      { term: "Jejuno", definition: "Porção média do intestino delgado." },
      { term: "Íleo", definition: "Porção final do intestino delgado." },
      { term: "Válvula Ileocecal", definition: "Válvula entre íleo e ceco." },
      { term: "Vilosidades Intestinais", definition: "Projeções da mucosa intestinal que aumentam absorção." },
      { term: "Microvilosidades", definition: "Projeções microscópicas das células intestinais." },
      { term: "Intestino Grosso", definition: "Segmento final do tubo digestivo que absorve água e forma fezes." },
      { term: "Ceco", definition: "Primeira porção do intestino grosso." },
      { term: "Apêndice Vermiforme", definition: "Pequena estrutura tubular ligada ao ceco." },
      { term: "Cólon Ascendente", definition: "Porção do intestino grosso que sobe no lado direito." },
      { term: "Cólon Transverso", definition: "Porção do intestino grosso que cruza o abdome." },
      { term: "Cólon Descendente", definition: "Porção do intestino grosso que desce no lado esquerdo." },
      { term: "Cólon Sigmoide", definition: "Porção em forma de S entre cólon descendente e reto." },
      { term: "Reto", definition: "Porção final do intestino grosso antes do ânus." },
      { term: "Canal Anal", definition: "Porção terminal do tubo digestivo." },
      { term: "Ânus", definition: "Abertura externa do canal anal." },
      { term: "Esfíncter Anal Interno", definition: "Músculo involuntário do ânus." },
      { term: "Esfíncter Anal Externo", definition: "Músculo voluntário do ânus." },
      { term: "Fígado", definition: "Maior glândula do corpo, responsável por múltiplas funções metabólicas." },
      { term: "Lobo Hepático Direito", definition: "Maior lobo do fígado." },
      { term: "Lobo Hepático Esquerdo", definition: "Menor lobo do fígado." },
      { term: "Lobo Caudado", definition: "Pequeno lobo posterior do fígado." },
      { term: "Lobo Quadrado", definition: "Pequeno lobo inferior do fígado." },
      { term: "Porta Hepática", definition: "Região onde vasos entram no fígado." },
      { term: "Hepatócito", definition: "Célula funcional do fígado." },
      { term: "Bile", definition: "Líquido produzido pelo fígado para digestão de gorduras." },
      { term: "Ducto Hepático", definition: "Canal que drena bile do fígado." },
      { term: "Vesícula Biliar", definition: "Órgão que armazena e concentra bile produzida pelo fígado." },
      { term: "Ducto Cístico", definition: "Canal entre vesícula biliar e ducto biliar comum." },
      { term: "Ducto Biliar Comum", definition: "Canal que transporta bile ao duodeno." },
      { term: "Pâncreas", definition: "Glândula mista com funções endócrinas e exócrinas." },
      { term: "Cabeça do Pâncreas", definition: "Porção do pâncreas adjacente ao duodeno." },
      { term: "Corpo do Pâncreas", definition: "Porção central do pâncreas." },
      { term: "Cauda do Pâncreas", definition: "Porção terminal do pâncreas próxima ao baço." },
      { term: "Ducto Pancreático", definition: "Canal que drena secreções pancreáticas ao duodeno." },
      { term: "Ilhotas de Langerhans", definition: "Grupos de células endócrinas no pâncreas." },
      { term: "Baço", definition: "Órgão linfoide que filtra sangue e armazena células sanguíneas." },
      { term: "Peritônio", definition: "Membrana serosa que reveste a cavidade abdominal." },
      { term: "Peritônio Parietal", definition: "Camada do peritônio aderida à parede abdominal." },
      { term: "Peritônio Visceral", definition: "Camada do peritônio que cobre órgãos." },
      { term: "Cavidade Peritoneal", definition: "Espaço potencial entre as camadas do peritônio." },
      { term: "Mesentério", definition: "Dobra do peritônio que suspende órgãos abdominais." },
      { term: "Omento Maior", definition: "Grande prega de peritônio que pende do estômago." },
      { term: "Omento Menor", definition: "Prega de peritônio entre estômago e fígado." },
      { term: "Mesocólon", definition: "Mesentério do intestino grosso." },
      { term: "Ligamento Falciforme", definition: "Ligamento que fixa fígado à parede anterior do abdome." },
      { term: "Peristaltismo", definition: "Contrações musculares que movem conteúdo pelo tubo digestivo." },
      { term: "Deglutição", definition: "Ato de engolir." },
      { term: "Digestão", definition: "Processo de quebra de alimentos em nutrientes absorvíveis." },
      { term: "Absorção", definition: "Passagem de nutrientes do tubo digestivo para o sangue." },
      { term: "Quimo", definition: "Massa semilíquida de alimento parcialmente digerido no estômago." },
      { term: "Quilo", definition: "Líquido leitoso contendo gorduras absorvidas no intestino." },
    ],
  },
  {
    category: "Sistema Urinário",
    terms: [
      { term: "Rim", definition: "Órgão responsável pela filtração do sangue e produção de urina." },
      { term: "Ureter", definition: "Tubo que conduz urina do rim à bexiga." },
      { term: "Bexiga", definition: "Órgão que armazena urina antes da micção." },
      { term: "Uretra", definition: "Canal que conduz urina da bexiga para o exterior." },
      { term: "Néfron", definition: "Unidade funcional do rim responsável pela filtração." },
      { term: "Glomérulo", definition: "Rede de capilares no néfron onde ocorre filtração." },
      { term: "Cápsula de Bowman", definition: "Estrutura que envolve o glomérulo e coleta o filtrado." },
      { term: "Túbulo Renal", definition: "Estrutura tubular do néfron onde ocorre reabsorção e secreção." },
      { term: "Túbulo Contorcido Proximal", definition: "Primeira porção do túbulo renal." },
      { term: "Alça de Henle", definition: "Porção em forma de U do túbulo renal." },
      { term: "Túbulo Contorcido Distal", definition: "Porção final do túbulo renal." },
      { term: "Ducto Coletor", definition: "Túbulo que recebe urina de vários néfrons." },
      { term: "Pelve Renal", definition: "Estrutura em forma de funil que coleta urina no rim." },
      { term: "Cálice Renal", definition: "Estrutura que coleta urina das papilas renais." },
      { term: "Cálice Maior", definition: "Cálice formado pela união de cálices menores." },
      { term: "Cálice Menor", definition: "Cálice que recebe urina diretamente das papilas." },
      { term: "Hilo Renal", definition: "Região côncava do rim por onde entram e saem vasos e ureter." },
      { term: "Córtex Renal", definition: "Camada externa do rim contendo corpúsculos renais." },
      { term: "Medula Renal", definition: "Camada interna do rim contendo pirâmides renais." },
      { term: "Pirâmide Renal", definition: "Estrutura cônica na medula renal." },
      { term: "Papila Renal", definition: "Ápice da pirâmide renal que libera urina." },
      { term: "Coluna Renal", definition: "Extensão do córtex entre as pirâmides." },
      { term: "Cápsula Renal", definition: "Membrana fibrosa que envolve o rim." },
      { term: "Corpúsculo Renal", definition: "Estrutura formada por glomérulo e cápsula de Bowman." },
      { term: "Filtração Glomerular", definition: "Processo de filtração do sangue no glomérulo." },
      { term: "Reabsorção Tubular", definition: "Retorno de substâncias úteis do filtrado ao sangue." },
      { term: "Secreção Tubular", definition: "Passagem de substâncias do sangue ao filtrado." },
      { term: "Taxa de Filtração Glomerular", definition: "Volume de sangue filtrado pelos rins por minuto." },
      { term: "Artéria Renal", definition: "Artéria que supre sangue ao rim." },
      { term: "Veia Renal", definition: "Veia que drena sangue do rim." },
      { term: "Arteríola Aferente", definition: "Vaso que leva sangue ao glomérulo." },
      { term: "Arteríola Eferente", definition: "Vaso que leva sangue do glomérulo." },
      { term: "Aparelho Justaglomerular", definition: "Estrutura que regula pressão arterial e filtração." },
      { term: "Mácula Densa", definition: "Células sensoras no túbulo distal." },
      { term: "Trígono Vesical", definition: "Região triangular na base da bexiga." },
      { term: "Músculo Detrusor", definition: "Músculo liso da parede da bexiga." },
      { term: "Esfíncter Uretral Interno", definition: "Músculo involuntário no colo da bexiga." },
      { term: "Esfíncter Uretral Externo", definition: "Músculo voluntário da uretra." },
      { term: "Micção", definition: "Ato de urinar." },
      { term: "Urina", definition: "Líquido excretado pelos rins." },
      { term: "Glândula Suprarrenal", definition: "Glândula endócrina localizada sobre o rim." },
      { term: "Clearance Renal", definition: "Taxa de remoção de uma substância do sangue pelos rins." },
      { term: "Diurese", definition: "Produção e eliminação de urina." },
      { term: "Oligúria", definition: "Diminuição anormal da produção de urina." },
      { term: "Anúria", definition: "Ausência de produção de urina." },
      { term: "Poliúria", definition: "Produção excessiva de urina." },
      { term: "Insuficiência Renal", definition: "Perda da capacidade dos rins de filtrar o sangue adequadamente." },
    ],
  },
  {
    category: "Sistema Genital",
    terms: [
      { term: "Testículo", definition: "Gônada masculina que produz espermatozoides e hormônios." },
      { term: "Epidídimo", definition: "Estrutura onde espermatozoides amadurecem e são armazenados." },
      { term: "Ducto Deferente", definition: "Canal que transporta espermatozoides do epidídimo." },
      { term: "Próstata", definition: "Glândula masculina que produz parte do líquido seminal." },
      { term: "Vesícula Seminal", definition: "Glândula que produz secreção nutritiva para espermatozoides." },
      { term: "Glândula Bulbouretral", definition: "Glândula que produz muco lubrificante na uretra masculina." },
      { term: "Escroto", definition: "Bolsa de pele que contém os testículos." },
      { term: "Pênis", definition: "Órgão copulatório masculino." },
      { term: "Corpo Cavernoso", definition: "Estrutura erétil do pênis." },
      { term: "Corpo Esponjoso", definition: "Estrutura erétil que envolve a uretra peniana." },
      { term: "Glande", definition: "Extremidade do pênis." },
      { term: "Prepúcio", definition: "Pele que cobre a glande." },
      { term: "Uretra Prostática", definition: "Porção da uretra que atravessa a próstata." },
      { term: "Uretra Membranácea", definition: "Porção curta da uretra após a próstata." },
      { term: "Uretra Esponjosa", definition: "Porção da uretra dentro do pênis." },
      { term: "Cordão Espermático", definition: "Estrutura que suspende o testículo e contém vasos e ductos." },
      { term: "Túnica Vaginal", definition: "Membrana serosa que envolve o testículo." },
      { term: "Túnica Albugínea", definition: "Cápsula fibrosa do testículo." },
      { term: "Túbulo Seminífero", definition: "Túbulo onde ocorre produção de espermatozoides." },
      { term: "Células de Sertoli", definition: "Células de suporte nos túbulos seminíferos." },
      { term: "Células de Leydig", definition: "Células que produzem testosterona." },
      { term: "Espermatogênese", definition: "Processo de produção de espermatozoides." },
      { term: "Espermatozoide", definition: "Célula reprodutiva masculina." },
      { term: "Sêmen", definition: "Fluido contendo espermatozoides e secreções glandulares." },
      { term: "Ejaculação", definition: "Expulsão do sêmen." },
      { term: "Ereção", definition: "Endurecimento e aumento do pênis por enchimento vascular." },
      { term: "Ovário", definition: "Gônada feminina que produz óvulos e hormônios." },
      { term: "Folículo Ovariano", definition: "Estrutura que contém e nutre o óvulo em desenvolvimento." },
      { term: "Corpo Lúteo", definition: "Estrutura endócrina formada após ovulação." },
      { term: "Ovulação", definition: "Liberação do óvulo maduro do ovário." },
      { term: "Tuba Uterina", definition: "Canal que conduz óvulo do ovário ao útero." },
      { term: "Fímbrias", definition: "Projeções na extremidade da tuba uterina que captam o óvulo." },
      { term: "Útero", definition: "Órgão muscular onde ocorre desenvolvimento fetal." },
      { term: "Fundo Uterino", definition: "Porção superior do útero acima das tubas." },
      { term: "Corpo Uterino", definition: "Porção central e maior do útero." },
      { term: "Istmo Uterino", definition: "Porção estreita entre corpo e colo uterino." },
      { term: "Colo Uterino", definition: "Porção inferior do útero que se projeta na vagina." },
      { term: "Óstio Uterino Interno", definition: "Abertura interna do canal cervical." },
      { term: "Óstio Uterino Externo", definition: "Abertura externa do canal cervical." },
      { term: "Canal Cervical", definition: "Canal que atravessa o colo uterino." },
      { term: "Endométrio", definition: "Camada interna do útero que se renova ciclicamente." },
      { term: "Miométrio", definition: "Camada muscular do útero responsável por contrações." },
      { term: "Perimétrio", definition: "Camada serosa externa do útero." },
      { term: "Vagina", definition: "Canal muscular que conecta útero ao exterior." },
      { term: "Fórnice Vaginal", definition: "Recesso ao redor do colo uterino." },
      { term: "Hímen", definition: "Membrana que cobre parcialmente a abertura vaginal." },
      { term: "Vulva", definition: "Conjunto de estruturas genitais externas femininas." },
      { term: "Monte do Púbis", definition: "Elevação de tecido adiposo sobre a sínfise púbica." },
      { term: "Grandes Lábios", definition: "Pregas externas de pele e tecido adiposo da vulva." },
      { term: "Pequenos Lábios", definition: "Pregas internas de mucosa da vulva." },
      { term: "Clitóris", definition: "Órgão erétil feminino sensível." },
      { term: "Vestíbulo Vaginal", definition: "Espaço entre os pequenos lábios." },
      { term: "Óstio Vaginal", definition: "Abertura externa da vagina." },
      { term: "Óstio Uretral Externo", definition: "Abertura externa da uretra feminina." },
      { term: "Glândula de Bartholin", definition: "Glândula que secreta muco lubrificante no vestíbulo." },
      { term: "Glândula de Skene", definition: "Glândulas ao redor da uretra feminina." },
      { term: "Glândula Mamária", definition: "Glândula modificada que produz leite." },
      { term: "Mama", definition: "Órgão que contém a glândula mamária." },
      { term: "Mamilo", definition: "Projeção da mama onde se abrem ductos lactíferos." },
      { term: "Aréola", definition: "Área pigmentada ao redor do mamilo." },
      { term: "Lobo Mamário", definition: "Divisão da glândula mamária." },
      { term: "Lóbulo Mamário", definition: "Subdivisão do lobo mamário contendo alvéolos." },
      { term: "Ducto Lactífero", definition: "Canal que conduz leite ao mamilo." },
      { term: "Seio Lactífero", definition: "Dilatação do ducto lactífero próximo ao mamilo." },
      { term: "Menstruação", definition: "Descamação cíclica do endométrio." },
      { term: "Ciclo Menstrual", definition: "Ciclo de mudanças hormonais e uterinas." },
      { term: "Fase Folicular", definition: "Primeira fase do ciclo ovariano." },
      { term: "Fase Lútea", definition: "Segunda fase do ciclo ovariano após ovulação." },
      { term: "Gravidez", definition: "Estado de gestação." },
      { term: "Placenta", definition: "Órgão que conecta feto à mãe durante gravidez." },
      { term: "Cordão Umbilical", definition: "Estrutura que conecta feto à placenta." },
      { term: "Parto", definition: "Processo de nascimento." },
      { term: "Lactação", definition: "Produção de leite." },
    ],
  },
  {
    category: "Sistema Nervoso",
    terms: [
      {
        term: "Nervo",
        definition: "Estrutura que transmite impulsos elétricos entre o sistema nervoso central e o corpo.",
      },
      { term: "Medula Espinal", definition: "Estrutura nervosa que se estende da base do crânio até a região lombar." },
      { term: "Cone Medular", definition: "Extremidade inferior afilada da medula espinal." },
      { term: "Cauda Equina", definition: "Conjunto de raízes nervosas que se estendem abaixo do cone medular." },
      { term: "Plexo", definition: "Rede de nervos ou vasos sanguíneos entrelaçados." },
      { term: "Dermátomo", definition: "Área da pele inervada por um único nervo espinal." },
      { term: "Inervação", definition: "Suprimento nervoso de uma região ou órgão." },
      { term: "Sistema Nervoso Central", definition: "Composto por encéfalo e medula espinal." },
      { term: "Sistema Nervoso Periférico", definition: "Composto por nervos e gânglios fora do SNC." },
      { term: "Neurônio", definition: "Célula nervosa especializada na transmissão de impulsos." },
      { term: "Neurônio Motor", definition: "Neurônio que transmite impulsos do SNC aos músculos." },
      { term: "Neurônio Sensitivo", definition: "Neurônio que transmite impulsos dos receptores ao SNC." },
      { term: "Interneurônio", definition: "Neurônio que conecta outros neurônios no SNC." },
      { term: "Corpo Celular", definition: "Parte do neurônio que contém o núcleo." },
      { term: "Dendrito", definition: "Prolongamento do neurônio que recebe sinais." },
      { term: "Axônio", definition: "Prolongamento do neurônio que transmite impulsos." },
      { term: "Bainha de Mielina", definition: "Camada isolante ao redor de axônios." },
      { term: "Nódulo de Ranvier", definition: "Espaço entre células de mielina." },
      { term: "Sinapse", definition: "Junção entre dois neurônios onde ocorre transmissão de sinais." },
      { term: "Fenda Sináptica", definition: "Espaço entre neurônios na sinapse." },
      { term: "Neurotransmissor", definition: "Substância química que transmite sinais entre neurônios." },
      { term: "Gânglio", definition: "Agrupamento de corpos celulares de neurônios fora do SNC." },
      { term: "Nervo Espinal", definition: "Nervo que emerge da medula espinal." },
      { term: "Raiz Dorsal", definition: "Raiz sensitiva de um nervo espinal." },
      { term: "Raiz Ventral", definition: "Raiz motora de um nervo espinal." },
      { term: "Gânglio da Raiz Dorsal", definition: "Gânglio sensitivo na raiz dorsal." },
      { term: "Substância Branca", definition: "Tecido nervoso composto principalmente por axônios mielinizados." },
      { term: "Substância Cinzenta", definition: "Tecido nervoso composto principalmente por corpos celulares." },
      { term: "Corno Anterior", definition: "Região ventral da substância cinzenta medular com neurônios motores." },
      { term: "Corno Posterior", definition: "Região dorsal da substância cinzenta medular com neurônios sensitivos." },
      { term: "Corno Lateral", definition: "Região da substância cinzenta com neurônios autônomos." },
      { term: "Funículo", definition: "Coluna de substância branca na medula espinal." },
      { term: "Trato Nervoso", definition: "Feixe de axônios no SNC." },
      { term: "Encéfalo", definition: "Parte do sistema nervoso central contida no crânio." },
      { term: "Cérebro", definition: "Maior parte do encéfalo responsável por funções superiores." },
      { term: "Hemisfério Cerebral", definition: "Uma das duas metades do cérebro." },
      { term: "Córtex Cerebral", definition: "Camada externa de substância cinzenta do cérebro." },
      { term: "Lobo Frontal", definition: "Parte anterior do cérebro envolvida em funções motoras e executivas." },
      { term: "Lobo Parietal", definition: "Parte do cérebro envolvida em sensações somáticas." },
      { term: "Lobo Temporal", definition: "Parte lateral do cérebro envolvida em audição e memória." },
      { term: "Lobo Occipital", definition: "Parte posterior do cérebro responsável pela visão." },
      { term: "Corpo Caloso", definition: "Feixe de fibras que conecta os hemisférios cerebrais." },
      { term: "Giro", definition: "Elevação na superfície do cérebro." },
      { term: "Sulco", definition: "Depressão na superfície do cérebro." },
      { term: "Fissura Longitudinal", definition: "Sulco profundo entre os hemisférios cerebrais." },
      { term: "Sulco Central", definition: "Sulco que separa lobos frontal e parietal." },
      { term: "Sulco Lateral", definition: "Sulco que separa lobo temporal dos lobos frontal e parietal." },
      { term: "Cerebelo", definition: "Parte do encéfalo responsável por coordenação e equilíbrio." },
      { term: "Vermis Cerebelar", definition: "Porção mediana do cerebelo." },
      { term: "Hemisfério Cerebelar", definition: "Uma das duas metades laterais do cerebelo." },
      { term: "Pedúnculo Cerebelar", definition: "Feixe de fibras que conecta cerebelo ao tronco encefálico." },
      { term: "Tronco Encefálico", definition: "Estrutura que conecta cérebro e medula espinal." },
      { term: "Mesencéfalo", definition: "Porção superior do tronco encefálico." },
      { term: "Ponte", definition: "Porção média do tronco encefálico." },
      { term: "Bulbo", definition: "Porção inferior do tronco encefálico." },
      { term: "Aqueduto Cerebral", definition: "Canal que conecta ventrículos no mesencéfalo." },
      { term: "Quarto Ventrículo", definition: "Cavidade entre tronco encefálico e cerebelo." },
      { term: "Diencéfalo", definition: "Parte do encéfalo entre cérebro e mesencéfalo." },
      { term: "Tálamo", definition: "Estrutura que relé informações sensoriais ao córtex." },
      { term: "Hipotálamo", definition: "Estrutura que regula funções autônomas e endócrinas." },
      { term: "Epitálamo", definition: "Estrutura dorsal do diencéfalo que contém a glândula pineal." },
      { term: "Glândula Pineal", definition: "Glândula endócrina que produz melatonina." },
      { term: "Núcleo da Base", definition: "Grupo de núcleos envolvidos no controle motor." },
      { term: "Sistema Límbico", definition: "Sistema envolvido em emoções e memória." },
      { term: "Hipocampo", definition: "Estrutura do sistema límbico envolvida na memória." },
      { term: "Amígdala", definition: "Estrutura do sistema límbico envolvida em emoções." },
      { term: "Meninges", definition: "Membranas que envolvem e protegem o sistema nervoso central." },
      { term: "Dura-máter", definition: "Meninge mais externa e resistente." },
      { term: "Aracnoide", definition: "Meninge intermediária com aspecto de teia de aranha." },
      { term: "Pia-máter", definition: "Meninge mais interna e delicada, aderida ao tecido nervoso." },
      { term: "Espaço Epidural", definition: "Espaço entre dura-máter e osso." },
      { term: "Espaço Subdural", definition: "Espaço potencial entre dura-máter e aracnoide." },
      { term: "Espaço Subaracnoide", definition: "Espaço entre aracnoide e pia-máter contendo líquor." },
      {
        term: "Líquido Cefalorraquidiano",
        definition: "Fluido que circula no sistema nervoso central, oferecendo proteção.",
      },
      { term: "Plexo Coroide", definition: "Estrutura que produz líquido cefalorraquidiano." },
      { term: "Ventrículo Cerebral", definition: "Cavidade no encéfalo contendo líquor." },
      { term: "Ventrículo Lateral", definition: "Cavidade em cada hemisfério cerebral." },
      { term: "Terceiro Ventrículo", definition: "Cavidade mediana no diencéfalo." },
      { term: "Nervo Craniano", definition: "Um dos 12 pares de nervos que emergem do encéfalo." },
      { term: "Nervo Olfatório", definition: "I par craniano, responsável pelo olfato." },
      { term: "Nervo Óptico", definition: "II par craniano, responsável pela visão." },
      { term: "Nervo Oculomotor", definition: "III par craniano, move a maioria dos músculos do olho." },
      { term: "Nervo Troclear", definition: "IV par craniano, move músculo oblíquo superior do olho." },
      { term: "Nervo Trigêmeo", definition: "V par craniano, responsável pela sensibilidade da face." },
      { term: "Nervo Abducente", definition: "VI par craniano, move músculo reto lateral do olho." },
      { term: "Nervo Facial", definition: "VII par craniano, responsável pela expressão facial." },
      { term: "Nervo Vestibulococlear", definition: "VIII par craniano, responsável por audição e equilíbrio." },
      { term: "Nervo Glossofaríngeo", definition: "IX par craniano, inerva língua e faringe." },
      { term: "Nervo Vago", definition: "X par craniano, com ampla distribuição visceral." },
      { term: "Nervo Acessório", definition: "XI par craniano, inerva trapézio e esternocleidomastóideo." },
      { term: "Nervo Hipoglosso", definition: "XII par craniano, move a língua." },
      { term: "Plexo Cervical", definition: "Rede de nervos espinais cervicais." },
      { term: "Plexo Braquial", definition: "Rede de nervos que inerva membro superior." },
      { term: "Plexo Lombossacral", definition: "Rede de nervos que inerva membro inferior." },
      { term: "Plexo Lombar", definition: "Porção superior do plexo lombossacral." },
      { term: "Plexo Sacral", definition: "Porção inferior do plexo lombossacral." },
      { term: "Nervo Frênico", definition: "Nervo que inerva o diafragma." },
      { term: "Nervo Ciático", definition: "Maior nervo do corpo que inerva membro inferior." },
      { term: "Nervo Mediano", definition: "Nervo que inerva parte anterior do antebraço e mão." },
      { term: "Nervo Radial", definition: "Nervo que inerva músculos extensores do membro superior." },
      { term: "Nervo Ulnar", definition: "Nervo que inerva músculos intrínsecos da mão." },
      { term: "Nervo Femoral", definition: "Nervo que inerva músculos anteriores da coxa." },
      { term: "Nervo Tibial", definition: "Ramo do nervo ciático que inerva parte posterior da perna." },
      { term: "Nervo Fibular", definition: "Ramo do nervo ciático que inerva parte lateral da perna." },
      { term: "Gânglio Cervical Superior", definition: "Gânglio simpático no pescoço." },
      {
        term: "Gânglio Estrelado",
        definition: "Gânglio simpático formado pela fusão de gânglios cervical inferior e torácico.",
      },
      { term: "Cadeia Simpática", definition: "Série de gânglios simpáticos ao longo da coluna vertebral." },
      {
        term: "Sistema Nervoso Autônomo",
        definition: "Divisão do sistema nervoso que controla funções involuntárias.",
      },
      { term: "Sistema Simpático", definition: "Divisão do SNA que prepara corpo para situações de estresse." },
      { term: "Sistema Parassimpático", definition: "Divisão do SNA que promove repouso e digestão." },
      { term: "Sistema Nervoso Entérico", definition: "Rede nervosa no trato gastrointestinal." },
      { term: "Acetilcolina", definition: "Neurotransmissor do sistema parassimpático." },
      { term: "Noradrenalina", definition: "Neurotransmissor do sistema simpático." },
      { term: "Dopamina", definition: "Neurotransmissor envolvido em movimento e recompensa." },
      { term: "Serotonina", definition: "Neurotransmissor envolvido em humor e sono." },
      { term: "GABA", definition: "Principal neurotransmissor inibitório do SNC." },
      { term: "Glutamato", definition: "Principal neurotransmissor excitatório do SNC." },
      { term: "Reflexo", definition: "Resposta automática e involuntária a um estímulo." },
      { term: "Arco Reflexo", definition: "Via neural que medeia um reflexo." },
      { term: "Receptor Sensorial", definition: "Estrutura especializada que detecta estímulos." },
      { term: "Propriocepção", definition: "Percepção da posição e movimento do corpo no espaço." },
      { term: "Nocicepção", definition: "Percepção de estímulos dolorosos." },
      { term: "Somestesia", definition: "Sensibilidade corporal geral incluindo tato, temperatura e dor." },
      { term: "Via Ascendente", definition: "Via nervosa que leva informações sensitivas ao encéfalo." },
      { term: "Via Descendente", definition: "Via nervosa que leva comandos motores do encéfalo." },
      { term: "Trato Corticoespinal", definition: "Via descendente para controle motor voluntário." },
      { term: "Neurologia", definition: "Estudo científico do sistema nervoso." },
      { term: "Neuroplasticidade", definition: "Capacidade do sistema nervoso de se reorganizar." },
      { term: "Potencial de Ação", definition: "Impulso elétrico que viaja pelo axônio." },
      { term: "Potencial de Repouso", definition: "Diferença de voltagem através da membrana neuronal em repouso." },
      { term: "Despolarização", definition: "Mudança no potencial de membrana tornando-o menos negativo." },
      { term: "Repolarização", definition: "Retorno do potencial de membrana ao estado de repouso." },
      { term: "AVC", definition: "Acidente Vascular Cerebral, interrupção do fluxo sanguíneo ao cérebro." },
      { term: "Epilepsia", definition: "Distúrbio neurológico caracterizado por convulsões recorrentes." },
      { term: "Parkinson", definition: "Doença neurodegenerativa que afeta movimentos." },
      { term: "Alzheimer", definition: "Doença neurodegenerativa que causa demência." },
      { term: "Esclerose Múltipla", definition: "Doença autoimune que afeta mielina no SNC." },
    ],
  },
  {
    category: "Sistema Endócrino",
    terms: [
      { term: "Glândula Endócrina", definition: "Glândula que secreta hormônios diretamente no sangue." },
      { term: "Hormônio", definition: "Mensageiro químico secretado por glândulas endócrinas." },
      { term: "Hipófise", definition: "Glândula mestra que controla outras glândulas endócrinas." },
      { term: "Adeno-hipófise", definition: "Lobo anterior da hipófise." },
      { term: "Neuro-hipófise", definition: "Lobo posterior da hipófise." },
      { term: "Hormônio do Crescimento", definition: "Hormônio que estimula crescimento e desenvolvimento." },
      { term: "Prolactina", definition: "Hormônio que estimula produção de leite." },
      { term: "ACTH", definition: "Hormônio adrenocorticotrófico que estimula glândulas suprarrenais." },
      { term: "TSH", definition: "Hormônio tireoestimulante que estimula tireoide." },
      { term: "FSH", definition: "Hormônio folículo-estimulante que atua nas gônadas." },
      { term: "LH", definition: "Hormônio luteinizante que atua nas gônadas." },
      { term: "Ocitocina", definition: "Hormônio que estimula contrações uterinas e ejeção de leite." },
      { term: "Vasopressina", definition: "Hormônio antidiurético que regula balanço hídrico." },
      { term: "Tireoide", definition: "Glândula endócrina que regula metabolismo." },
      { term: "Lobo Tireoidiano", definition: "Uma das duas porções laterais da tireoide." },
      { term: "Istmo Tireoidiano", definition: "Porção que conecta os lobos da tireoide." },
      { term: "Folículo Tireoidiano", definition: "Unidade funcional da tireoide." },
      { term: "Hormônio Tireoidiano", definition: "T3 e T4, hormônios que regulam metabolismo." },
      { term: "Tiroxina", definition: "T4, principal hormônio produzido pela tireoide." },
      { term: "Triiodotironina", definition: "T3, forma mais ativa do hormônio tireoidiano." },
      { term: "Calcitonina", definition: "Hormônio que reduz cálcio sanguíneo." },
      { term: "Paratireoide", definition: "Glândulas que regulam níveis de cálcio no sangue." },
      { term: "Paratormônio", definition: "Hormônio que aumenta cálcio sanguíneo." },
      { term: "Suprarrenal", definition: "Glândula localizada sobre os rins que produz hormônios do estresse." },
      { term: "Córtex Suprarrenal", definition: "Camada externa da glândula suprarrenal." },
      { term: "Medula Suprarrenal", definition: "Camada interna da glândula suprarrenal." },
      { term: "Cortisol", definition: "Hormônio glicocorticoide que regula metabolismo e estresse." },
      { term: "Aldosterona", definition: "Hormônio mineralocorticoide que regula eletrólitos." },
      { term: "Adrenalina", definition: "Hormônio do estresse produzido pela medula suprarrenal." },
      { term: "Noradrenalina Endócrina", definition: "Hormônio do estresse similar à adrenalina." },
      { term: "Pâncreas Endócrino", definition: "Função endócrina do pâncreas produzindo hormônios." },
      { term: "Insulina", definition: "Hormônio que reduz glicose sanguínea." },
      { term: "Glucagon", definition: "Hormônio que aumenta glicose sanguínea." },
      { term: "Somatostatina", definition: "Hormônio que inibe secreção de insulina e glucagon." },
      { term: "Célula Beta Pancreática", definition: "Célula que produz insulina." },
      { term: "Célula Alfa Pancreática", definition: "Célula que produz glucagon." },
      { term: "Célula Delta Pancreática", definition: "Célula que produz somatostatina." },
      { term: "Glândula Pineal Endócrina", definition: "Glândula que produz melatonina." },
      { term: "Melatonina", definition: "Hormônio que regula ciclo sono-vigília." },
      { term: "Timo Endócrino", definition: "Órgão que produz hormônios tímicos." },
      { term: "Timosina", definition: "Hormônio que promove maturação de linfócitos T." },
      { term: "Testosterona", definition: "Principal hormônio sexual masculino." },
      { term: "Estrogênio", definition: "Principal hormônio sexual feminino." },
      { term: "Progesterona", definition: "Hormônio que prepara útero para gravidez." },
      { term: "Diabetes Mellitus", definition: "Doença caracterizada por hiperglicemia crônica." },
      { term: "Diabetes Insípido", definition: "Doença por deficiência de vasopressina." },
      { term: "Hipertireoidismo", definition: "Produção excessiva de hormônios tireoidianos." },
      { term: "Hipotireoidismo", definition: "Produção insuficiente de hormônios tireoidianos." },
      { term: "Síndrome de Cushing", definition: "Excesso de cortisol no organismo." },
      { term: "Doença de Addison", definition: "Insuficiência das glândulas suprarrenais." },
      { term: "Gigantismo", definition: "Crescimento excessivo por excesso de GH na infância." },
      { term: "Acromegalia", definition: "Crescimento excessivo de extremidades por excesso de GH no adulto." },
      { term: "Nanismo Hipofisário", definition: "Baixa estatura por deficiência de GH." },
    ],
  },
  {
    category: "Sistema Linfático",
    terms: [
      { term: "Linfonodo", definition: "Estrutura do sistema linfático que filtra a linfa." },
      { term: "Linfa", definition: "Fluido intersticial que circula no sistema linfático." },
      { term: "Vaso Linfático", definition: "Canal que transporta linfa." },
      { term: "Capilar Linfático", definition: "Menor vaso linfático que absorve fluido intersticial." },
      { term: "Vaso Linfático Aferente", definition: "Vaso que leva linfa ao linfonodo." },
      { term: "Vaso Linfático Eferente", definition: "Vaso que leva linfa do linfonodo." },
      { term: "Ducto Torácico", definition: "Maior vaso linfático que drena linfa para o sistema venoso." },
      { term: "Ducto Linfático Direito", definition: "Vaso linfático que drena lado superior direito do corpo." },
      { term: "Cisterna do Quilo", definition: "Dilatação na base do ducto torácico." },
      { term: "Timo", definition: "Órgão linfoide onde ocorre maturação de linfócitos T." },
      { term: "Baço Linfático", definition: "Maior órgão linfoide que filtra sangue." },
      { term: "Polpa Branca", definition: "Tecido linfoide do baço." },
      { term: "Polpa Vermelha", definition: "Tecido do baço que filtra sangue." },
      { term: "Amígdala", definition: "Tecido linfoide na faringe que participa da defesa imunológica." },
      { term: "Amígdala Palatina", definition: "Amígdala localizada nas paredes laterais da orofaringe." },
      { term: "Amígdala Faríngea", definition: "Amígdala na parede posterior da nasofaringe." },
      { term: "Amígdala Lingual", definition: "Tecido linfoide na base da língua." },
      { term: "Anel de Waldeyer", definition: "Conjunto de tecidos linfoides na faringe." },
      { term: "Tecido Linfoide Associado à Mucosa", definition: "MALT, tecido imune em mucosas." },
      { term: "Placas de Peyer", definition: "Agregados linfoides no intestino delgado." },
      { term: "Apêndice Linfoide", definition: "Tecido linfoide no apêndice vermiforme." },
      { term: "Linfócito", definition: "Célula imune principal do sistema linfático." },
      { term: "Linfócito T", definition: "Linfócito que matura no timo." },
      { term: "Linfócito B", definition: "Linfócito que produz anticorpos." },
      { term: "Linfócito NK", definition: "Célula natural killer, parte da imunidade inata." },
      { term: "Macrófago", definition: "Célula fagocítica do sistema imune." },
      { term: "Célula Dendrítica", definition: "Célula apresentadora de antígenos." },
      { term: "Imunidade Inata", definition: "Resposta imune não específica e imediata." },
      { term: "Imunidade Adaptativa", definition: "Resposta imune específica e com memória." },
      { term: "Antígeno", definition: "Substância que desencadeia resposta imune." },
      { term: "Anticorpo", definition: "Proteína que reconhece e neutraliza antígenos." },
      { term: "Imunoglobulina", definition: "Outra denominação para anticorpo." },
      { term: "Edema Linfático", definition: "Acúmulo de linfa nos tecidos." },
      { term: "Linfedema", definition: "Inchaço por bloqueio da drenagem linfática." },
      { term: "Linfadenite", definition: "Inflamação de linfonodos." },
      { term: "Linfangite", definition: "Inflamação de vasos linfáticos." },
      { term: "Esplenomegalia", definition: "Aumento do tamanho do baço." },
    ],
  },
  {
    category: "Tecidos e Histologia",
    terms: [
      { term: "Histologia", definition: "Estudo dos tecidos." },
      { term: "Tecido", definition: "Grupo de células com estrutura e função semelhantes." },
      { term: "Tecido Epitelial", definition: "Tecido que reveste superfícies e forma glândulas." },
      { term: "Epitélio Simples", definition: "Epitélio com uma camada de células." },
      { term: "Epitélio Estratificado", definition: "Epitélio com múltiplas camadas de células." },
      { term: "Epitélio Pavimentoso", definition: "Epitélio com células achatadas." },
      { term: "Epitélio Cúbico", definition: "Epitélio com células em forma de cubo." },
      { term: "Epitélio Cilíndrico", definition: "Epitélio com células alongadas." },
      { term: "Epitélio Pseudoestratificado", definition: "Epitélio que parece estratificado mas não é." },
      { term: "Epitélio de Transição", definition: "Epitélio que muda de forma, encontrado na bexiga." },
      { term: "Epitélio Glandular", definition: "Epitélio especializado em secreção." },
      { term: "Glândula Exócrina", definition: "Glândula que secreta para ductos." },
      { term: "Glândula Endócrina", definition: "Glândula que secreta hormônios no sangue." },
      { term: "Glândula Mista", definition: "Glândula com funções exócrina e endócrina." },
      { term: "Tecido Conjuntivo", definition: "Tecido de suporte e conexão." },
      { term: "Tecido Conjuntivo Frouxo", definition: "Tecido conjuntivo com fibras esparsas." },
      { term: "Tecido Conjuntivo Denso", definition: "Tecido conjuntivo com fibras densamente empacotadas." },
      { term: "Tecido Adiposo", definition: "Tecido conjuntivo especializado em armazenar gordura." },
      { term: "Cartilagem", definition: "Tecido conjuntivo firme e flexível." },
      { term: "Cartilagem Hialina", definition: "Tipo mais comum de cartilagem." },
      { term: "Cartilagem Elástica", definition: "Cartilagem com fibras elásticas." },
      { term: "Fibrocartilagem", definition: "Cartilagem com abundantes fibras colágenas." },
      { term: "Tecido Ósseo", definition: "Tecido conjuntivo rígido e mineralizado." },
      { term: "Osteócito", definition: "Célula óssea madura." },
      { term: "Osteoblasto", definition: "Célula que forma osso." },
      { term: "Osteoclasto", definition: "Célula que reabsorve osso." },
      { term: "Matriz Óssea", definition: "Substância mineralizada entre células ósseas." },
      { term: "Tecido Sanguíneo", definition: "Tecido conjuntivo líquido." },
      { term: "Plasma Sanguíneo", definition: "Parte líquida do sangue." },
      { term: "Eritrócito", definition: "Glóbulo vermelho, transporta oxigênio." },
      { term: "Leucócito", definition: "Glóbulo branco, célula de defesa." },
      { term: "Plaqueta", definition: "Fragmento celular envolvido em coagulação." },
      { term: "Hemácia", definition: "Outro nome para eritrócito." },
      { term: "Neutrófilo", definition: "Tipo de leucócito fagocítico." },
      { term: "Eosinófilo", definition: "Leucócito envolvido em alergias e parasitas." },
      { term: "Basófilo", definition: "Leucócito que libera histamina." },
      { term: "Monócito", definition: "Leucócito que se transforma em macrófago." },
      { term: "Hematopoiese", definition: "Processo de produção de células sanguíneas." },
      { term: "Tecido Muscular Esquelético", definition: "Músculo estriado voluntário." },
      { term: "Tecido Muscular Liso", definition: "Músculo não estriado involuntário." },
      { term: "Tecido Muscular Cardíaco", definition: "Músculo estriado involuntário do coração." },
      { term: "Tecido Nervoso", definition: "Tecido especializado em condução de impulsos." },
      { term: "Neuróglia", definition: "Células de suporte do tecido nervoso." },
      { term: "Astrócito", definition: "Célula glial de suporte no SNC." },
      { term: "Oligodendrócito", definition: "Célula glial que forma mielina no SNC." },
      { term: "Célula de Schwann", definition: "Célula que forma mielina no SNP." },
      { term: "Micróglia", definition: "Célula imune do SNC." },
      { term: "Célula Ependimária", definition: "Célula que reveste ventrículos." },
      { term: "Membrana Basal", definition: "Camada sob epitélios." },
      { term: "Matriz Extracelular", definition: "Material entre células em tecido conjuntivo." },
      { term: "Colágeno", definition: "Proteína fibrosa abundante no tecido conjuntivo." },
      { term: "Elastina", definition: "Proteína que confere elasticidade aos tecidos." },
      { term: "Fibroblasto", definition: "Célula que produz fibras do tecido conjuntivo." },
      { term: "Membrana Serosa", definition: "Membrana que reveste cavidades fechadas." },
      { term: "Membrana Mucosa", definition: "Membrana que reveste cavidades abertas ao exterior." },
      { term: "Membrana Cutânea", definition: "A pele, maior membrana do corpo." },
    ],
  },
  {
    category: "Sistema Tegumentar",
    terms: [
      { term: "Pele", definition: "Maior órgão do corpo que forma barreira protetora." },
      { term: "Epiderme", definition: "Camada externa da pele." },
      { term: "Derme", definition: "Camada intermediária da pele com vasos e nervos." },
      { term: "Hipoderme", definition: "Camada subcutânea de tecido adiposo." },
      { term: "Queratinócito", definition: "Célula mais abundante da epiderme." },
      { term: "Melanócito", definition: "Célula que produz melanina." },
      { term: "Melanina", definition: "Pigmento que dá cor à pele." },
      { term: "Camada Córnea", definition: "Camada mais superficial da epiderme com células mortas." },
      { term: "Camada Basal", definition: "Camada mais profunda da epiderme com células em divisão." },
      { term: "Derme Papilar", definition: "Camada superficial da derme." },
      { term: "Derme Reticular", definition: "Camada profunda da derme com fibras densas." },
      { term: "Folículo Piloso", definition: "Estrutura que produz pelo." },
      { term: "Pelo", definition: "Filamento de queratina que cresce da pele." },
      { term: "Glândula Sebácea", definition: "Glândula que secreta sebo." },
      { term: "Glândula Sudorípara", definition: "Glândula que produz suor." },
      { term: "Glândula Sudorípara Écrina", definition: "Glândula de suor para termorregulação." },
      { term: "Glândula Sudorípara Apócrina", definition: "Glândula de suor em axilas e virilha." },
      { term: "Unha", definition: "Placa de queratina nas extremidades dos dedos." },
      { term: "Leito Ungueal", definition: "Pele sob a unha." },
      { term: "Lúnula", definition: "Área branca em forma de meia-lua na base da unha." },
      { term: "Cutícula", definition: "Pele que cobre a base da unha." },
      { term: "Receptor Sensorial Cutâneo", definition: "Terminação nervosa na pele." },
      { term: "Corpúsculo de Meissner", definition: "Receptor de tato fino." },
      { term: "Corpúsculo de Pacini", definition: "Receptor de pressão profunda." },
      { term: "Termorregulação", definition: "Controle da temperatura corporal." },
      { term: "Queimadura de 1º Grau", definition: "Lesão superficial da epiderme." },
      { term: "Queimadura de 2º Grau", definition: "Lesão que atinge derme." },
      { term: "Queimadura de 3º Grau", definition: "Lesão que destrói toda espessura da pele." },
    ],
  },
  {
    category: "Órgãos dos Sentidos",
    terms: [
      { term: "Olho", definition: "Órgão da visão." },
      { term: "Globo Ocular", definition: "Estrutura esférica do olho." },
      { term: "Córnea", definition: "Parte transparente anterior do olho." },
      { term: "Esclera", definition: "Camada branca externa do olho." },
      { term: "Íris", definition: "Parte colorida do olho que controla pupila." },
      { term: "Pupila", definition: "Abertura central da íris." },
      { term: "Cristalino", definition: "Lente do olho que focaliza imagens." },
      { term: "Retina", definition: "Camada interna do olho com fotorreceptores." },
      { term: "Coroide", definition: "Camada vascular entre esclera e retina." },
      { term: "Mácula", definition: "Área central da retina para visão detalhada." },
      { term: "Fóvea", definition: "Centro da mácula com maior acuidade visual." },
      { term: "Nervo Óptico Sensorial", definition: "Nervo que transmite informações visuais ao cérebro." },
      { term: "Ponto Cego", definition: "Região sem fotorreceptores onde o nervo óptico sai." },
      { term: "Bastonete", definition: "Fotorreceptor para visão em baixa luz." },
      { term: "Cone", definition: "Fotorreceptor para visão de cores." },
      { term: "Humor Aquoso", definition: "Líquido entre córnea e cristalino." },
      { term: "Humor Vítreo", definition: "Substância gelatinosa que preenche globo ocular." },
      { term: "Pálpebra", definition: "Dobra de pele que protege o olho." },
      { term: "Cílios", definition: "Pelos nas bordas das pálpebras." },
      { term: "Conjuntiva", definition: "Membrana que reveste pálpebra e esclera." },
      { term: "Glândula Lacrimal", definition: "Glândula que produz lágrimas." },
      { term: "Ducto Lacrimal", definition: "Canal que drena lágrimas." },
      { term: "Músculo Ocular Extrínseco", definition: "Músculo que move o globo ocular." },
      { term: "Músculo Reto Medial", definition: "Músculo que move olho para dentro." },
      { term: "Músculo Reto Lateral", definition: "Músculo que move olho para fora." },
      { term: "Músculo Reto Superior", definition: "Músculo que eleva o olho." },
      { term: "Músculo Reto Inferior", definition: "Músculo que abaixa o olho." },
      { term: "Músculo Oblíquo Superior", definition: "Músculo que roda o olho para baixo e lateral." },
      { term: "Músculo Oblíquo Inferior", definition: "Músculo que roda o olho para cima e lateral." },
      { term: "Acomodação Visual", definition: "Ajuste do cristalino para focar." },
      { term: "Orelha Externa", definition: "Parte do ouvido que capta som." },
      { term: "Pavilhão Auricular", definition: "Parte externa visível da orelha." },
      { term: "Meato Acústico Externo", definition: "Canal que conduz som ao tímpano." },
      { term: "Membrana Timpânica", definition: "Tímpano, vibra com ondas sonoras." },
      { term: "Orelha Média", definition: "Cavidade com ossículos da audição." },
      { term: "Martelo", definition: "Primeiro ossículo da audição." },
      { term: "Bigorna", definition: "Segundo ossículo da audição." },
      { term: "Estribo", definition: "Terceiro ossículo da audição." },
      { term: "Tuba Auditiva", definition: "Canal que equilibra pressão na orelha média." },
      { term: "Orelha Interna", definition: "Parte do ouvido com órgãos da audição e equilíbrio." },
      { term: "Cóclea", definition: "Estrutura em espiral para audição." },
      { term: "Órgão de Corti", definition: "Órgão sensorial da audição na cóclea." },
      { term: "Vestíbulo Auricular", definition: "Parte da orelha interna para equilíbrio." },
      { term: "Canais Semicirculares", definition: "Estruturas para detectar rotação da cabeça." },
      { term: "Utrículo", definition: "Órgão do equilíbrio que detecta aceleração linear." },
      { term: "Sáculo", definition: "Órgão do equilíbrio sensível à gravidade." },
      { term: "Nervo Vestibular", definition: "Parte do VIII par craniano para equilíbrio." },
      { term: "Nervo Coclear", definition: "Parte do VIII par craniano para audição." },
      { term: "Endolinfa", definition: "Líquido dentro do labirinto membranoso." },
      { term: "Perilinfa", definition: "Líquido entre labirintos ósseo e membranoso." },
      { term: "Gustação", definition: "Sentido do paladar." },
      { term: "Botão Gustativo", definition: "Receptor de paladar na língua." },
      { term: "Olfação", definition: "Sentido do olfato." },
      { term: "Epitélio Olfatório", definition: "Tecido com receptores olfatórios no nariz." },
      { term: "Célula Olfatória", definition: "Neurônio sensorial do olfato." },
      { term: "Bulbo Olfatório", definition: "Estrutura cerebral que processa informações olfatórias." },
      { term: "Tato", definition: "Sentido que detecta pressão e textura." },
      { term: "Dor", definition: "Sensação desagradável indicando lesão." },
      { term: "Temperatura", definition: "Sensação de calor ou frio." },
    ],
  },
  {
    category: "Estruturas Gerais e Termos Clínicos",
    terms: [
      { term: "Hérnia", definition: "Protrusão de órgão ou tecido através de abertura anormal." },
      { term: "Canal Inguinal", definition: "Passagem na parede abdominal inferior." },
      { term: "Segmentação", definition: "Princípio de organização corporal em unidades repetidas." },
      { term: "Esplancnologia", definition: "Estudo científico das vísceras e órgãos internos." },
      { term: "Homeostase", definition: "Manutenção do equilíbrio interno do corpo." },
      { term: "Metabolismo", definition: "Conjunto de reações químicas no organismo." },
      { term: "Anabolismo", definition: "Processos metabólicos de síntese." },
      { term: "Catabolismo", definition: "Processos metabólicos de degradação." },
      { term: "pH", definition: "Medida de acidez ou alcalinidade." },
      { term: "Eletrólito", definition: "Mineral ionizado em fluidos corporais." },
      { term: "Edema", definition: "Acúmulo anormal de líquido nos tecidos." },
      { term: "Inflamação", definition: "Resposta do corpo a lesão ou infecção." },
      { term: "Necrose", definition: "Morte de células ou tecidos." },
      { term: "Apoptose", definition: "Morte celular programada." },
      { term: "Hipertrofia", definition: "Aumento do tamanho de células ou órgãos." },
      { term: "Hiperplasia", definition: "Aumento do número de células." },
      { term: "Atrofia", definition: "Diminuição do tamanho de células ou órgãos." },
      { term: "Metaplasia", definition: "Transformação de um tipo celular em outro." },
      { term: "Displasia", definition: "Desenvolvimento anormal de células." },
      { term: "Neoplasia", definition: "Crescimento anormal de tecido, tumor." },
      { term: "Tumor Benigno", definition: "Crescimento não invasivo e não metastático." },
      { term: "Tumor Maligno", definition: "Câncer, crescimento invasivo com metástase." },
      { term: "Metástase", definition: "Disseminação de células cancerosas." },
      { term: "Biópsia", definition: "Remoção de tecido para exame." },
      { term: "Hemostasia", definition: "Processo de parada de sangramento." },
      { term: "Coagulação", definition: "Formação de coágulo sanguíneo." },
      { term: "Fibrina", definition: "Proteína que forma rede no coágulo." },
      { term: "Hematoma", definition: "Acúmulo localizado de sangue fora dos vasos." },
      { term: "Hemorragia", definition: "Sangramento, perda de sangue." },
      { term: "Anemia", definition: "Redução de hemoglobina ou eritrócitos." },
      { term: "Hemoglobina", definition: "Proteína que transporta oxigênio nos eritrócitos." },
      { term: "Hipóxia", definition: "Deficiência de oxigênio nos tecidos." },
      { term: "Anóxia", definition: "Ausência total de oxigênio." },
      { term: "Cianose", definition: "Coloração azulada da pele por falta de oxigênio." },
      { term: "Icterícia", definition: "Coloração amarelada da pele por excesso de bilirrubina." },
      { term: "Ascite", definition: "Acúmulo de líquido na cavidade peritoneal." },
      { term: "Dispneia", definition: "Dificuldade para respirar." },
      { term: "Apneia", definition: "Parada respiratória temporária." },
      { term: "Taquipneia", definition: "Respiração rápida." },
      { term: "Bradipneia", definition: "Respiração lenta." },
      { term: "Taquicardia", definition: "Frequência cardíaca elevada." },
      { term: "Bradicardia", definition: "Frequência cardíaca baixa." },
      { term: "Arritmia", definition: "Ritmo cardíaco irregular." },
      { term: "Hipertensão", definition: "Pressão arterial elevada." },
      { term: "Hipotensão", definition: "Pressão arterial baixa." },
      { term: "Choque", definition: "Estado de perfusão inadequada dos tecidos." },
      { term: "Sepse", definition: "Resposta inflamatória sistêmica a infecção." },
      { term: "Febre", definition: "Elevação da temperatura corporal." },
      { term: "Hipotermia", definition: "Temperatura corporal abaixo do normal." },
      { term: "Desidratação", definition: "Perda excessiva de água corporal." },
      { term: "Nutrição", definition: "Processo de obtenção e uso de nutrientes." },
      { term: "Obesidade", definition: "Acúmulo excessivo de gordura corporal." },
      { term: "Desnutrição", definition: "Deficiência de nutrientes." },
      { term: "Vitamina", definition: "Substância orgânica essencial em pequenas quantidades." },
      { term: "Mineral", definition: "Elemento inorgânico essencial para o corpo." },
    ],
  },
]

// Manter compatibilidade com código existente
export const glossaryTerms = glossaryByCategory
  .flatMap((category) => category.terms)
  .sort((a, b) => a.term.localeCompare(b.term))
